Implement BranchNode.
world-federation-of-advertisers/virtual-people-core-serving pull request #6
Opened 2021-06-01 21:14 UTC by tcsnfkx

Create C++ implemention for BranchNode. Seleting child node by chance or condition is supported currently. Attributes updater and multipilicity will be implemented in future.

Add a method in ModelNode to resolve the child node index references.

2021-06-01 21:59 UTC, efoxepstein requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 8 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8Wisw065ab3QgX40H:-Mb8Wisw065ab3QgX40I:b-mzddf7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L29)):*
> ```objc
> namespace wfa_virtual_people {
> 
> typedef std::variant<uint32_t, std::unique_ptr<ModelNode>> ChildNodeRef;
> ```

1. Please use `using` instead of `typedef`.
2. Please use `absl::variant` instead of `std::variant`.
3. Please document what each case means.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XAZB9utY5_6VAgDy:-Mb8XAZB9utY5_6VAgDz:bvwrvn0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L81)):*
> ```objc
>   // TODO(@tcsnfkx): Resolve the child references of the UpdateTree if exists.
>   absl::Status ResolveChildReferences(
>       absl::flat_hash_map<uint32_t, std::unique_ptr<ModelNode>>* node_refs
> ```

Please use a mutable reference unless you want this to be nullable.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XEmA4PihNGwjrHKa:-Mb8XEmB5KO5wQVl87tI:bvwrvn0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L86)):*
> ```objc
>   // Uses @hashing_ or @matcher_ to select one of the ModelNodes in
>   // @child_nodes_, and apply the selected ModelNode.
>   absl::Status Apply(LabelerEvent* event) const override;
> ```

Please use a mutable reference unless you want this to be nullable.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XZe3CrwVJY-l-yC6:-Mb8XZe3CrwVJY-l-yC7:bvwrvn0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L36)):*
> ```cpp
>     const BranchNode::Branch& branch,
>     const ModelNodeFactory& factory,
>     std::vector<ChildNodeRef>* child_nodes) {
> ```

Please use a mutable reference unless you want this to be nullable.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XLmY-3YQFHuzsQLN:-Mb8XLmY-3YQFHuzsQLO:bmp3h9g) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L42)):*
> ```cpp
>     child_nodes->emplace_back(branch.node_index());
>     return absl::OkStatus();
>   } else if (branch.has_node()) {
> ```

`else` not needed because `if`-branch always returns.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8YbBrCa1r6fg5DjhB:-Mb8YbBrCa1r6fg5DjhC:bxhwdad) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L150)):*
> ```cpp
>           "The ModelNode object of the child ndoe index is not provided.");
>     }
>     child_node.emplace<1>(std::move(node_refs->at(node_index)));
> ```

This is doing an unnecessary triple lookup.

How about:

```
auto it = node_refs->find(node_index);
if (it == node_refs->end()) { ... }
child_node.emplace<1>(std::move(it->second));
node_refs->erase(it);
```

or even:

```
auto node = node_refs->extract(node_index);
if (node.key() != node_index) { ... }
child_node.emplace<1>(std::move(it->second));
```
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8_8Ci4LzOvIhJUV5P:-Mb8_8Cm8ssw0vzRUPZG:bzau9gj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L187)):*
> ```cpp
>     }
>   }
>   if (child_nodes_[selected_index].index() != 1) {
> ```

You're doing a double-lookup here, how about:

```
SomeType child_node = child_nodes_[selected_index];
```
___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8_OkyDgtHVUqIEQ7N:-Mb8_OkyDgtHVUqIEQ7O:b-fgexx3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.cc#L38)):*
> ```cpp
>   // Converts each FieldFilterProto to FieldFilter. Breaks if encounters any
>   // error status.
>   std::vector<std::unique_ptr<FieldFilter>> filters;
> ```

Here and elsewhere: how big are these vectors going to be typically? Consider using absl::InlinedVector: https://github.com/abseil/abseil-cpp/blob/master/absl/container/inlined_vector.h -- this could save a lot of heap allocations.


<!-- Sent from Reviewable.io -->

2021-06-02 06:40 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 6 of 14 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8Wisw065ab3QgX40H:-MbAQCIMBrTv4yZCWc5N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

1. Please use `using` instead of `typedef`.
2. Please use `absl::variant` instead of `std::variant`.
3. Please document what each case means.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XAZB9utY5_6VAgDy:-MbAQHVoEuPQ0OG_A-ft:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L81)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use a mutable reference unless you want this to be nullable.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XEmA4PihNGwjrHKa:-MbAQIZeAAU8zMg7RI0F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L86)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use a mutable reference unless you want this to be nullable.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XZe3CrwVJY-l-yC6:-MbAQJxG2jhAGGp4aSBZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use a mutable reference unless you want this to be nullable.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8XLmY-3YQFHuzsQLN:-MbAQMAkA0K2nVGosFdq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`else` not needed because `if`-branch always returns.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8YbBrCa1r6fg5DjhB:-MbAQRIH-ZS78kQRzgzB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L150)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is doing an unnecessary triple lookup.

How about:

```
auto it = node_refs->find(node_index);
if (it == node_refs->end()) { ... }
child_node.emplace<1>(std::move(it->second));
node_refs->erase(it);
```

or even:

```
auto node = node_refs->extract(node_index);
if (node.key() != node_index) { ... }
child_node.emplace<1>(std::move(it->second));
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8_8Ci4LzOvIhJUV5P:-MbAQTeoDxWT3_vt62lG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L187)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You're doing a double-lookup here, how about:

```
SomeType child_node = child_nodes_[selected_index];
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8_OkyDgtHVUqIEQ7N:-MbAQWIx59L367JO9yQI:byf9q9o) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/412cf85ece31880dab06bc932ed7c1e2e7eee50c/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.cc#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Here and elsewhere: how big are these vectors going to be typically? Consider using absl::InlinedVector: https://github.com/abseil/abseil-cpp/blob/master/absl/container/inlined_vector.h -- this could save a lot of heap allocations.
</blockquote></details>

We expect the size of the vectors to be larger than 20 in most cases. I think it is unnecessary to use absl::InlinedVector. We can visit this again if the performance is not good.


<!-- Sent from Reviewable.io -->

2021-06-02 16:29 UTC, efoxepstein approved these changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbCUx8L30YrBQQ0Q0O7:-MbCUx8L30YrBQQ0Q0O8:bjjgypf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L43)):*
> ```objc
> // TODO(@tcsnfkx): Implement attributes updater.
> // TODO(@tcsnfkx): Implement multiplicity.
> class BranchNodeImpl : public ModelNode {
> ```

Why BranchNodeImpl instead of just BranchNode?
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbCWbqP34oDeI56gp8e:-MbCWbqP34oDeI56gp8f:b-k8fq8k) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L79)):*
> ```cpp
>   bool has_chance = false;
>   bool has_condition = false;
>   for (const BranchNode::Branch& branch : branch_node.branches()) {
> ```

I'm wondering if it would be more efficient to just check the first element here instead of looping over everything. Then in the cases below you can have something like:

```
    for (const BranchNode::Branch& branch : branch_node.branches()) {
      if (!branch.has_chance()) { return absl::InvalidArgumentError(...); }
      distribution.emplace_back(DistributionChoice({index, branch.chance()}));
      ++index;
    }
 ```

Alternatively, right before you declare `hashing = nullptr` below, you can do:

```
if (has_chance == has_condition) return absl::InvalidArgumentError(...);
```

That allows you to simplify your if-statements to just `if (has_chance)` and `else`
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbCXgKe-YHzLfrW2jCt:-MbCXgKe-YHzLfrW2jCu:b-y65s3v) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L150)):*
https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

> Minimize the use of abbreviations that would likely be unknown to someone outside your project (especially acronyms and initialisms). .... As a rule of thumb, an abbreviation is probably OK if it's listed in Wikipedia. 

I'd just write "node" here.


<!-- Sent from Reviewable.io -->

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h
> +  absl::Status ResolveChildReferences(
Should this be on ModelNode interface? We expect to only do it once starting from root node, correct?

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h
> +  BranchNodeImpl(const BranchNodeImpl&) = delete;
Move up to after ctor/dtor?

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h
> +  // used to select the first child node whose condition matches.
Could add " when Apply is called" to match hashing_.

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc
> +      node_refs[2],
-> node_refs[population_node_config_1.index()]

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc
> +      node_refs[3],
-> node_refs[population_node_config_2.index()]

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc
> +}
Add a test case for nested child reference, i.e. a node_index child also uses node_index.

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/model_node.h
> +  virtual absl::Status ResolveChildReferences(
Should this be on ModelNode, or just a factory function?

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.cc
> +  return -1;
Use a constant to indicate no_match. And the caller can check using the constant, rather than being coupled with this.

2021-06-02 17:38 UTC, wliue commented on src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h
> +  // Returns -1 if no matching.
Use a constant for no_match.

2021-06-03 06:08 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 9 of 14 files reviewed, 22 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbCUx8L30YrBQQ0Q0O7:-MbE1BOmD97ehy3TLunY:b-pkqb8k) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why BranchNodeImpl instead of just BranchNode?
</blockquote></details>

BranchNode is already used by the protobuf in the same namespace.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04b-r2-52:-MbFShwh1qtOYuWoShUG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L52)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: the meaning of "neither ... nor ... in at least one" is ambiguous.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04b-r2-85:-MbEBddQ5ZodAxKyYAUG:b-j2ki7i) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L85)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Should this be on ModelNode interface? We expect to only do it once starting from root node, correct?
</blockquote></details>

Yes. This PR added this method to ModelNode interface also. In Labeler API, we will call this on root node.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04b-r2-93:-MbFSx9v5yMvh-1WXY45:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L93)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Move up to after ctor/dtor?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h, line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04b-r2-110:-MbFT-bbC0QcsD-AHcmV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.h#L110)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add " when Apply is called" to match hashing_.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-72:-MbFT5NJ73l2DtQOVexM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L72)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

chance and condition are oneof. Maybe the following is a little easier to reason about:
- if all have chance: use chance
- if all have condition: use condition
- else return error

Alternatively, use the first branch to determine whether to use chance or condition. Then check that the rest has the same setting.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbCWbqP34oDeI56gp8e:-MbFT7VWAVniNWwN13C-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm wondering if it would be more efficient to just check the first element here instead of looping over everything. Then in the cases below you can have something like:

```
    for (const BranchNode::Branch& branch : branch_node.branches()) {
      if (!branch.has_chance()) { return absl::InvalidArgumentError(...); }
      distribution.emplace_back(DistributionChoice({index, branch.chance()}));
      ++index;
    }
 ```

Alternatively, right before you declare `hashing = nullptr` below, you can do:

```
if (has_chance == has_condition) return absl::InvalidArgumentError(...);
```

That allows you to simplify your if-statements to just `if (has_chance)` and `else`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-93:-MbFTAb17AteCZDn0xCd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L93)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Typo: consistent
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-113:-MbFTCa-292H3KWyNH2C:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L113)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

-> have the same type
</blockquote></details>

Removed.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-138:-MbFTJIX6BkTbHGeBeiK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L138)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could also mention that it is an error if not found.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-143:-MbFTKHH2sxcMFfwJWwJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L143)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Maybe use get_if<>?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/ [...]

2021-06-03 17:00 UTC, efoxepstein approved these changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 20 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbHmqku4x8P7ZsNGbet:-MbHmqku4x8P7ZsNGbeu:bln9ezr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5a59cb38959d891dbbc82176f4c0fa0a46bd3a2d/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L103)):*
> ```cpp
>   std::unique_ptr<DistributedConsistentHashing> hashing = nullptr;
>   std::unique_ptr<FieldFiltersMatcher> matcher = nullptr;
>   if (select_by == SelectBranchBy::CHANCE) {
> ```

Optional: consider pulling the bodies of these if-statements out into helper functions, so here you can have:

```
switch (select_by) {
  case CHANCE: ASSIGN_OR_RETURN(hashing, BuildDistributedConsistentHashing(branch_node)); break;
  case CONDITION: ASSIGN_OR_RETURN(matcher, BuildMatcher(branch_node)); break;
}
```

with helpers like:

```
absl::StatusOr<std::unique_ptr<DistributedConsistentHashing>> BuildDistributedConsistentHashing(const BranchNode& branch_node) {
    std::vector<DistributionChoice> distribution;
    int index = 0;
    for (const BranchNode::Branch& branch : branch_node.branches()) {
      distribution.emplace_back(DistributionChoice({index, branch.chance()}));
      ++index;
    }
    return DistributedConsistentHashing::Build(std::move(distribution));
}
```


<!-- Sent from Reviewable.io -->

2021-06-03 18:26 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 13 of 14 files reviewed, 19 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbHmqku4x8P7ZsNGbet:-MbI72Je2bQhCahWMOQW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5a59cb38959d891dbbc82176f4c0fa0a46bd3a2d/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Optional: consider pulling the bodies of these if-statements out into helper functions, so here you can have:

```
switch (select_by) {
  case CHANCE: ASSIGN_OR_RETURN(hashing, BuildDistributedConsistentHashing(branch_node)); break;
  case CONDITION: ASSIGN_OR_RETURN(matcher, BuildMatcher(branch_node)); break;
}
```

with helpers like:

```
absl::StatusOr<std::unique_ptr<DistributedConsistentHashing>> BuildDistributedConsistentHashing(const BranchNode& branch_node) {
    std::vector<DistributionChoice> distribution;
    int index = 0;
    for (const BranchNode::Branch& branch : branch_node.branches()) {
      distribution.emplace_back(DistributionChoice({index, branch.chance()}));
      ++index;
    }
    return DistributedConsistentHashing::Build(std::move(distribution));
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-03 18:43 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 13 of 14 files reviewed, 20 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 128 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbIAv_H4MWt4HP4Ybx9:-MbIAv_H4MWt4HP4YbxA:b-eqecky) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L128)):*
> ```cpp
>   std::unique_ptr<FieldFiltersMatcher> matcher = nullptr;
>   if (select_by == SelectBranchBy::CHANCE) {
>     ASSIGN_OR_RETURN(hashing, BuildHashing(branch_node.branches()));
> ```

Please use a switch on `select_by` so we know it's exhaustive coverage.


<!-- Sent from Reviewable.io -->

2021-06-03 18:46 UTC, efoxepstein reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 20 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)



<!-- Sent from Reviewable.io -->

2021-06-03 23:10 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 24 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-143:-MbJ-S7-A50Hu7lXuTik:b21k23j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L143)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Done.
</blockquote></details>


Maybe absl::get_if by type?
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-157:-MbJ-LOk6kV0uIAS_ayE:b21k23j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L157)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Done.
</blockquote></details>


Maybe absl::get_if by type?
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 183 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-183:-MbJ-DQzAmGr6-GhseYI:b-xcqjlp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L183)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Change to check for non-negative.
</blockquote></details>


Check against the NoMatch constant.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 193 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-193:-MbJ-oZP9AjTvY5OaguQ:b7xhmwv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L193)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe absl::get_if by type?
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbIw87D9huTmaQEmyCe:-MbIw87D9huTmaQEmyCf:b3cqbxp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L117)):*
> ```
> "BranchNode must have chance set."
> ```
This error message is not quite right. The error is more about "All branches should use the same select_by type."
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 121 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbIwbxR6qaLhPOliH1d:-MbIwbxSBMBz153RHPh3:b1atelm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L121)):*
> ```
>           "BranchNode must have condition set.");
> ```
This error message is not quite right. The error is more about "All branches should use the same select_by type."
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 207 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ6Wfp9e0f29CD-9Zf:-MbJ6Wfp9e0f29CD-9Zg:b-ovvdzc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L207)):*
> ```
>  const ChildNodeRef& selected_node = child_nodes_[selected_index];
> ```

Nit: add a blank line before.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ5nU91Dg23J4HVfxh:-MbJ5nU91Dg23J4HVfxi:b-e4e3pm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h#L25)):*
> ```
> constexpr int kNoMatchingIndex = -1;
> ```
inline this.


<!-- Sent from Reviewable.io -->

2021-06-04 00:56 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 13 of 14 files reviewed, 23 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-143:-MbJWAT6DHpvgnMZFrb9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L143)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Maybe absl::get_if by type?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-157:-MbJWAwJ606S3aSK2i9w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L157)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Maybe absl::get_if by type?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 183 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-183:-MbJWD2-EWnFv_knJXKM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L183)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Check against the NoMatch constant.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 193 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04a-r2-193:-MbJWEd-7iUVrzrKdsDF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L193)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Maybe absl::get_if by type?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbIw87D9huTmaQEmyCe:-MbJW7Qk1-g7UHwbeFH0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L117)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> "BranchNode must have chance set."
> ```
This error message is not quite right. The error is more about "All branches should use the same select_by type."
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 121 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbIwbxR6qaLhPOliH1d:-MbJW7zl9anrgazAMHWV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L121)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>           "BranchNode must have condition set.");
> ```
This error message is not quite right. The error is more about "All branches should use the same select_by type."
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 128 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbIAv_H4MWt4HP4Ybx9:-MbJW9EQDwcitbbX8V9Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L128)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use a switch on `select_by` so we know it's exhaustive coverage.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ5nU91Dg23J4HVfxh:-MbJVaFI7NDkMg7u_YK4:bj5tk0g) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h#L25)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> constexpr int kNoMatchingIndex = -1;
> ```
inline this.
</blockquote></details>

constexpr is implicitly inline.


<!-- Sent from Reviewable.io -->

2021-06-04 01:54 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 13 of 14 files reviewed, 23 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ5nU91Dg23J4HVfxh:-MbJgJjk4oT5VbZ6gjni:b-f56bgy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h#L25)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

constexpr is implicitly inline.
</blockquote></details>

constexpr function and static member variable are implicitly inline, but not namespace-scope variable. 
See https://en.cppreference.com/w/cpp/language/inline 


<!-- Sent from Reviewable.io -->

2021-06-04 06:59 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 12 of 14 files reviewed, 23 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ5nU91Dg23J4HVfxh:-MbKoTy90iwKHpftWZ10:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h#L25)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

constexpr function and static member variable are implicitly inline, but not namespace-scope variable. 
See https://en.cppreference.com/w/cpp/language/inline 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-04 18:54 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 23 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbNM57BEoXOb-bcjAkS:-MbNM57BEoXOb-bcjAkT:bcberww) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/297d8b757cc779ed6c06964fc3d3549611494ff1/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L34)):*
> ```cpp
> enum SelectBranchBy {
>   CHANCE = 1,
>   CONDITION = 2,
> ```

The proto compiler automatically generates an enum like this, accessible via the `oneof_name_case()` accessor: https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#oneof

Maybe using that would be simpler because you can say `SelectByCase case = branch_node.branches(0).select_by_case();` and then later do:

```
if (branch.select_by_case() != case) { return an error; }
```
___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ5nU91Dg23J4HVfxh:-MbNLJIx0TsBBBxtVw97:btmn6va) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h#L25)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For future reference: https://abseil.io/tips/140


<!-- Sent from Reviewable.io -->

2021-06-04 20:11 UTC, wliue approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 23 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/model_node.h, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04X-r2-46:-MbNdIpF0l8c2ZfD_3gZ:b-44ugve) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/model_node.h#L46)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

A factory function still requires to call the method in this interface to resolve the tree structure.
</blockquote></details>

Could add a comment that this method is intended to be only used (by Labeler) during model loading. 


<!-- Sent from Reviewable.io -->

2021-06-04 20:47 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: 12 of 14 files reviewed, 23 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbNM57BEoXOb-bcjAkS:-MbNlwWO0Px1xuj5Ou8R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/297d8b757cc779ed6c06964fc3d3549611494ff1/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The proto compiler automatically generates an enum like this, accessible via the `oneof_name_case()` accessor: https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#oneof

Maybe using that would be simpler because you can say `SelectByCase case = branch_node.branches(0).select_by_case();` and then later do:

```
if (branch.select_by_case() != case) { return an error; }
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/model_node.h, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-Mb8WfNMSo-q6SvXs04X-r2-46:-MbNlqvv2gPvXhS1rIrr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/14eca30e80a93f25fb72a89d4f5ab81c3bb3ac2f/src/main/cc/wfa/virtual_people/core/model/model_node.h#L46)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a comment that this method is intended to be only used (by Labeler) during model loading. 
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6#-MbJ5nU91Dg23J4HVfxh:-MbNlrrA-P46ITGKQUFj:b8zzliv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/26b3059faa2dd78b3e53aa6dcc707dfa798ff13e/src/main/cc/wfa/virtual_people/core/model/utils/field_filters_matcher.h#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For future reference: https://abseil.io/tips/140
</blockquote></details>

Acknowledge.


<!-- Sent from Reviewable.io -->

2021-06-04 20:52 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/6)* status: all files reviewed, 22 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)



<!-- Sent from Reviewable.io -->

2021-06-04 22:46 UTC, mpatel24 approved these changes

2021-06-05 04:50 UTC, tcsnfkx commented on src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc
>        // This should never happen.
Done.

2021-06-05 04:50 UTC, merged