Implement UpdateMatrix, and create interface for AttributesUpdater.
world-federation-of-advertisers/virtual-people-core-serving pull request #7
Opened 2021-06-07 18:20 UTC by tcsnfkx

2021-06-08 00:04 UTC, efoxepstein requested changes
> Reviewed 13 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: 13 of 18 files reviewed, 7 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 201 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbcsdIfC3P7XiPqky6x:-MbcsdIfC3P7XiPqky6y:b-pnnok3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L201)):*
> ```cpp
> absl::Status BranchNodeImpl::Apply(LabelerEvent& event) const {
>   // Applies attributes updaters.
>   for (auto& updater : updaters_) {
> ```

I'm wondering if we should defensively check that `updater` is not null here. Since this code is essentially allowing execution of untrusted inputs, we really want to avoid the possibility of maliciously crafted inputs causing problems.

We should also check other places where pointers are used and ensure that there are null checks.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 558 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbctQgg10fYHKjRX0hk:-MbctQgg10fYHKjRX0hl:b-tyygwm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L558)):*
> ```cpp
>     absl::string_view person_country_code = input.person_country_code();
>     EXPECT_TRUE(
>         person_country_code == "country_code_1" ||
> ```

How about:

```
EXPECT_THAT(
  std::pair(person_country_code, id),
  AnyOf(Pair("country_code_1", 10), Pair("country_code_2", 20))
);
```
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 593 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu1XFAVEd2FmydYvp:-Mbcu1XFAVEd2FmydYvq:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L593)):*
> ```cpp
>     int64_t id = input.virtual_person_activities(0).virtual_person_id();
>     if (person_country_code == "country_code_1") {
>       EXPECT_EQ(id, 10);
> ```

Ditto
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 676 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu5Fu6EFM2UnLrB-k:-Mbcu5Fu6EFM2UnLrB-l:bt1a9c4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L676)):*
> ```cpp
>   input.set_person_country_code("COUNTRY_1");
>   input.set_acting_fingerprint(1);
>   EXPECT_THAT(node->Apply(input), IsOk());
> ```

`ASSERT_THAT`?
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu_AjAScwKvWkbitq:-Mbcu_AjAScwKvWkbitr:b-xsk4pn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L53)):*
> ```objc
>       absl::string_view random_seed,
>       std::vector<LabelerEvent>&& rows,
>       bool pass_through_non_matches):
> ```

Consider making this an enum
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcv3vu-UtUxxt1UVvO:-Mbcv3vu-UtUxxt1UVvP:braf3en) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L96)):*
> ```cpp
>           config.probabilities(row_index * column_count + column_index);
>       distribution.emplace_back(
>           DistributionChoice({row_index, static_cast<double>(probability)}));
> ```

Emplace means you can just pass the DistributionChoice constructor arguments, rather than a DistributionChoice.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbcvE-PDzr08UKXEff1:-MbcvE-PDzr08UKXEff2:bft60rs) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L104)):*
> ```cpp
>   }
> 
>   std::vector<LabelerEvent> rows;
> ```

Can you do something like `std::vector<LabelerEvent> rows = {config.rows().begin(), config.rows().end()};` to build it all at once?


<!-- Sent from Reviewable.io -->

2021-06-08 06:09 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: 11 of 18 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 201 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbcsdIfC3P7XiPqky6x:-Mbe5X4Q0h3sgAqTTRiY:brtw2uh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L201)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm wondering if we should defensively check that `updater` is not null here. Since this code is essentially allowing execution of untrusted inputs, we really want to avoid the possibility of maliciously crafted inputs causing problems.

We should also check other places where pointers are used and ensure that there are null checks.
</blockquote></details>

I think null check is not necessary here, as we have full control of initialization of updaters_. It is ensured that AttributesUpdaterInterface::Build never returns nullptr.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 558 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbctQgg10fYHKjRX0hk:-MbeEF8D4HBSkfXvR2e3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L558)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about:

```
EXPECT_THAT(
  std::pair(person_country_code, id),
  AnyOf(Pair("country_code_1", 10), Pair("country_code_2", 20))
);
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 593 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu1XFAVEd2FmydYvp:-MbeEDeNETvcZA_kfF-T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L593)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 676 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu5Fu6EFM2UnLrB-k:-Mbe8Te68myCJ3bks-Xh:b-domk40) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L676)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`ASSERT_THAT`?
</blockquote></details>

This also tests that the attributes updaters works fine in the node.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu_AjAScwKvWkbitq:-Mbe8mNH3m12EI1sHZNi:b-4dfog9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consider making this an enum
</blockquote></details>

I think this is a definitely yes/no option, which is a good fit for boolean.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcv3vu-UtUxxt1UVvO:-MbeDQp3-08v2CTaGLXU:bc2l8c8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L96)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Emplace means you can just pass the DistributionChoice constructor arguments, rather than a DistributionChoice.
</blockquote></details>

It does not work for struct default constructor. https://stackoverflow.com/questions/20391632/how-to-use-stdvectoremplace-back-for-vectorvectorint
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbcvE-PDzr08UKXEff1:-MbeEGR2AqE_BwBTmqzd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L104)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you do something like `std::vector<LabelerEvent> rows = {config.rows().begin(), config.rows().end()};` to build it all at once?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-08 16:22 UTC, efoxepstein requested changes
> Reviewed 5 of 18 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: all files reviewed, 6 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 201 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbcsdIfC3P7XiPqky6x:-MbgOW1l2-RKx2MuOu7n:bud31zk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L201)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I think null check is not necessary here, as we have full control of initialization of updaters_. It is ensured that AttributesUpdaterInterface::Build never returns nullptr.
</blockquote></details>

How is it ensured? It might be the case right now, but this is an open source project with a bunch of contributors and over time preconditions get weakened unless there are strong enough tests and guardrails. The cost of sprinkling in some nullptr checks is pretty minimal and it could potentially avoid vulnerabilities. Adding the check in `Build` or the constructor seems fine too so there's less of a runtime penalty.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 676 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu5Fu6EFM2UnLrB-k:-MbgM2at4-LfP8qqd5jr:b-g02z6x) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L676)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

This also tests that the attributes updaters works fine in the node.
</blockquote></details>

I don't understand your comment. My suggestion is to replace `EXPECT_THAT` with `ASSERT_THAT` because it doesn't make sense to check `input.person_country_code()` if `node->Apply(input)` is not OK.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu_AjAScwKvWkbitq:-MbgQ-1FEFOeFUawVE6B:b-5f3tbz) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L53)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I think this is a definitely yes/no option, which is a good fit for boolean.
</blockquote></details>

https://abseil.io/tips/94 argues against boolean parameters. Yes/no doesn't necessarily mean that boolean is a good fit because it's not clear if `true` matches to yes or to no, or what the question even is. For example, the parameter could have just as easily been named `reject_non_matches`, which would give booleans the opposite meaning.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcv3vu-UtUxxt1UVvO:-MbgMCOC5_MDv1LRnOM3:b-vnivgu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L96)):*
Right, so there's no advantage to using `emplace_back` here instead of `push_back`. `emplace_back` will use a move-constructor for `DistributionChoice` whereas `push_back` will just directly move the argument into the right spot.

https://abseil.io/tips/112

> So in general, if both push_back() and emplace_back() would work with the same arguments, you should prefer push_back()
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.cc, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbgMwkb7lho6Divu2pY:-MbgMwkcAWifVb9iFcsm:b-mrvbyr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da8aeac9cbcf9f9f4e476100fbe1579d690f4e0e/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.cc#L62)):*
> ```cpp
>     }
>     uint64_t hash = HashLabelerEvent(*event, hash_field_mask);
>     if (hashes.find(hash) != hashes.end()) {
> ```

This is doing a double lookup. How about:

```
auto [iterator, inserted] = hashes.insert_or_assign(hash, index);
if (!inserted) {
  return absl::InvalidArgumentError("Muliple ...");
}
```
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc, line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbgO2fp2W7yDH09b8qv:-MbgO2fp2W7yDH09b8qw:b-dpysfl) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da8aeac9cbcf9f9f4e476100fbe1579d690f4e0e/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc#L134)):*
> ```cpp
>   events.emplace_back(&input_event_2);
> 
>   google::protobuf::FieldMask hash_field_mask;
> ```

What about a helper function like:

```
FieldMask MakeFieldMask(absl::Span<const std::string> paths) {
  FieldMask field_mask;
  for (const std::string& path : paths) { field_mask.add_paths(path); }
  return field_mask;
}
```

That could remove some boilerplate from the tests so it's easier to focus on what they're testing.


<!-- Sent from Reviewable.io -->

2021-06-08 23:55 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: 12 of 18 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 201 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbcsdIfC3P7XiPqky6x:-Mbi296M8-41BTgp8WL9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L201)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How is it ensured? It might be the case right now, but this is an open source project with a bunch of contributors and over time preconditions get weakened unless there are strong enough tests and guardrails. The cost of sprinkling in some nullptr checks is pretty minimal and it could potentially avoid vulnerabilities. Adding the check in `Build` or the constructor seems fine too so there's less of a runtime penalty.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 676 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu5Fu6EFM2UnLrB-k:-Mbi2BLR61jQJ90UUhBs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L676)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't understand your comment. My suggestion is to replace `EXPECT_THAT` with `ASSERT_THAT` because it doesn't make sense to check `input.person_country_code()` if `node->Apply(input)` is not OK.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcu_AjAScwKvWkbitq:-Mbi2Cf178eA7SF6I6w1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://abseil.io/tips/94 argues against boolean parameters. Yes/no doesn't necessarily mean that boolean is a good fit because it's not clear if `true` matches to yes or to no, or what the question even is. For example, the parameter could have just as easily been named `reject_non_matches`, which would give booleans the opposite meaning.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbcv3vu-UtUxxt1UVvO:-Mbi2EYv0aSlZKlalIhI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ddf37f4abe146b54eda78729eb2b7a63cd9a104/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L96)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Right, so there's no advantage to using `emplace_back` here instead of `push_back`. `emplace_back` will use a move-constructor for `DistributionChoice` whereas `push_back` will just directly move the argument into the right spot.

https://abseil.io/tips/112

> So in general, if both push_back() and emplace_back() would work with the same arguments, you should prefer push_back()
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.cc, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbgMwkb7lho6Divu2pY:-Mbi2HHeCUmMGtEaNaXg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da8aeac9cbcf9f9f4e476100fbe1579d690f4e0e/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is doing a double lookup. How about:

```
auto [iterator, inserted] = hashes.insert_or_assign(hash, index);
if (!inserted) {
  return absl::InvalidArgumentError("Muliple ...");
}
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc, line 134 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbgO2fp2W7yDH09b8qv:-Mbi2IYk51Eth2nIH5L1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da8aeac9cbcf9f9f4e476100fbe1579d690f4e0e/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc#L134)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What about a helper function like:

```
FieldMask MakeFieldMask(absl::Span<const std::string> paths) {
  FieldMask field_mask;
  for (const std::string& path : paths) { field_mask.add_paths(path); }
  return field_mask;
}
```

That could remove some boilerplate from the tests so it's easier to focus on what they're testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-09 16:15 UTC, efoxepstein approved these changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)



<!-- Sent from Reviewable.io -->

2021-06-10 00:06 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: all files reviewed, 8 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 135 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn7nGv6l1kzYkRNvGg:-Mbn7nGv6l1kzYkRNvGh:b678f1o) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L135)):*
> ```
>       if (!updaters.back()) {
> ```

We expect this won't happen, correct? Could add a comment.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 605 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn8qIK8H1NUqaYOm-O:-Mbn8qIK8H1NUqaYOm-P:b-n30esn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L605)):*
> ```cpp
> TEST(BranchNodeImplTest, TestApplyUpdateMatricesInOrder) {
>   // The branch node has 2 attributes updater and 1 branches.
>   // The 1st update matrix always chances person_country_code from COUNTRY_1 to
> ```

-> changes
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 607 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn8svBD5u99nvBoJJf:-Mbn8svBD5u99nvBoJJg:b-n30esn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L607)):*
> ```cpp
>   // The 1st update matrix always chances person_country_code from COUNTRY_1 to
>   // COUNTRY_2.
>   // The 2nd update matrix always chances person_country_code from COUNTRY_2 to
> ```

-> changes
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 664 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn9J2PCnkcQRTSS6DW:-Mbn9J2PCnkcQRTSS6DX:b-arx1kd) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L664)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>   // Test for COUNTRY_1
>   LabelerEvent input;
>   input.set_person_country_code("COUNTRY_1");
>   input.set_acting_fingerprint(1);
>   ASSERT_THAT(node->Apply(input), IsOk());
>   EXPECT_EQ(input.person_country_code(), "COUNTRY_3");
>   EXPECT_EQ(input.virtual_person_activities(0).virtual_person_id(), 10);
> ```
</details>

Could test multiple events.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn9luP6LpeP_1Hh1pY:-Mbn9luP6LpeP_1Hh1pZ:btef24w) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L73)):*
> ```objc
>   //
>   // Returns error status if no column matches @event, and
>   // pass_through_non_matches_ is false.
> ```

Update this comment now that it uses enum.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn9nw9CRCDUy7kMz4u:-Mbn9nw9CRCDUy7kMz4v:btef24w) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L92)):*
> ```objc
>   std::vector<LabelerEvent> rows_;
>   // When calling Update, if no column matches, returns OkStatus if
>   // pass_through_non_matches_ is true, otherwise returns error status.
> ```

Update this comment now that it uses enum.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.h, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbnCJ7mBzMChy3N19UR:-MbnCJ7mBzMChy3N19US:b-tf9yt8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.h#L35)):*
> ```objc
>   //   @events is empty.
>   //   Any entry in @events is null.
>   //   @hash_field_mask.paths is empty.
> ```

Also when there is collision.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbnE2kVE3lg5oNpvn1G:-MbnE2kW0RvYaIXf68DP:bidcz6t) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc#L101)):*
> ```cpp
>       HashFieldMaskMatcher::Build(events, hash_field_mask));
> 
>   // events[0] matches. Returns 0.
> ```

Could add a comment somewhere that only check fields in hash_field_mask, so person_region_code is ignored.


<!-- Sent from Reviewable.io -->

2021-06-10 06:07 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: 14 of 18 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 135 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn7nGv6l1kzYkRNvGg:-MboT48o1XNBudhHxj08:beu39z6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L135)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>       if (!updaters.back()) {
> ```

We expect this won't happen, correct? Could add a comment.
</blockquote></details>

This will not happen for now. But as mentioned in Eli's comments, it is possible that people check in code to create a nullptr in future. As this check is in initialization only, I think it is affordable.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 605 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn8qIK8H1NUqaYOm-O:-MboWvDM8HWfOvQcMdXN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L605)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

-> changes
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 607 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn8svBD5u99nvBoJJf:-MboWvbU79gkHnGDFR1m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L607)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

-> changes
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 664 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn9J2PCnkcQRTSS6DW:-MboWwQZ2m7bMpybu-uW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L664)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>   // Test for COUNTRY_1
>   LabelerEvent input;
>   input.set_person_country_code("COUNTRY_1");
>   input.set_acting_fingerprint(1);
>   ASSERT_THAT(node->Apply(input), IsOk());
>   EXPECT_EQ(input.person_country_code(), "COUNTRY_3");
>   EXPECT_EQ(input.virtual_person_activities(0).virtual_person_id(), 10);
> ```
Could test multiple events.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn9luP6LpeP_1Hh1pY:-MboWxKT94PHwRnDM2W4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L73)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Update this comment now that it uses enum.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h, line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbn9nw9CRCDUy7kMz4u:-MboWyZcBD0xlj1c61u9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.h#L92)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Update this comment now that it uses enum.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.h, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbnCJ7mBzMChy3N19UR:-MboX0m515uobjpRwoch:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher.h#L35)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Also when there is collision.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbnE2kVE3lg5oNpvn1G:-MboX1jW4A2CrU8_CySK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc#L101)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a comment somewhere that only check fields in hash_field_mask, so person_region_code is ignored.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-10 07:01 UTC, wliue approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbnE2kVE3lg5oNpvn1G:-Mboi6vh32cSh_JxCSQf:blclhw9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc#L101)):*
> ```
>   // person_region_code is ignored as not included in hash_field_mask.
> ```
Could also add comment for event_4.


<!-- Sent from Reviewable.io -->

2021-06-10 16:36 UTC, mpatel24 approved these changes

2021-06-10 18:11 UTC, efoxepstein reviewed
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 670 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbr6avhDvfEqvO5Sr8x:-Mbr6avhDvfEqvO5Sr8y:b-fqgkyp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/2a7da8b177a5a0aeb48639955d62afe9953a467d/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L670)):*
> ```cpp
>     ASSERT_THAT(node->Apply(input), IsOk());
>     EXPECT_EQ(input.person_country_code(), "COUNTRY_3");
>     EXPECT_EQ(input.virtual_person_activities(0).virtual_person_id(), 10);
> ```

Do we want to also verify that `acting_fingerprint` has not changed?


<!-- Sent from Reviewable.io -->

2021-06-10 18:46 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 670 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-Mbr6avhDvfEqvO5Sr8x:-MbrEoSS7BftYp5udmpb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/2a7da8b177a5a0aeb48639955d62afe9953a467d/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L670)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we want to also verify that `acting_fingerprint` has not changed?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7#-MbnE2kVE3lg5oNpvn1G:-MbrErvd8jGGJtFM_p2T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/49932940a0e4fc2c0a4da5a6e8b1e573e598f969/src/main/cc/wfa/virtual_people/core/model/utils/hash_field_mask_matcher_test.cc#L101)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>   // person_region_code is ignored as not included in hash_field_mask.
> ```
Could also add comment for event_4.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-10 18:47 UTC, merged