vid selector kotlin
world-federation-of-advertisers/virtual-people-core-serving pull request #73
Opened 2023-06-08 13:19 UTC by Marco-Premier

[TA673](https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F703920426175)

Kotlin Implementation of the VID selector for VID Model Distribution.

2023-06-08 13:19 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)
<!-- Reviewable:end -->

2023-06-09 15:48 UTC, kungfucraig requested changes
> Reviewed 21 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 21 of 23 files reviewed, 7 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVn2AF3KNeF_LT_RjZ:-NXVmDRp-lMAvr4mg3tb:b-aee2jc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt#L1)):*
> ```Kotlin
> // Copyright 2022 The Cross-Media Measurement Authors
> ```

This file name is kinda of weird. Maybe call it Hashing.kt or FarmHash.kt?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVnQki23RHyYPD0p73:-NXVnQki23RHyYPD0p74:b8naphs) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt#L19)):*
> ```Kotlin
> class LRUCache<K, V>(private val capacity: Int) : LinkedHashMap<K, V>(capacity) {
> 
>   override fun removeEldestEntry(eldest: MutableMap.MutableEntry<K, V>?): Boolean {
> ```

Can you add a comment about what this is doing?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVnWGK6aIZeaujf6oV:-NXVnWGK6aIZeaujf6oW:b-18bzxx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L20)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.ModelLine
> import org.wfanet.measurement.api.v2alpha.ModelRollout
> import org.wfanet.virtualpeople.common.*
> ```

@SanjayVas are we allowing import wildcards?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo2rL9GL7HOkRb2ow:-NXVo2rL9GL7HOkRb2ox:b-jul5ra) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L56)):*
> ```Kotlin
>       }
>     }
>     return null
> ```

Should we be throwing an exception if we cannot find a model release?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo_NSCdfleP6C96dZ:-NXVo_NSCdfleP6C96d_:byoxtx0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L60)):*
> ```Kotlin
> 
>   private fun readFromCache(eventDay: Long): ArrayList<Triple<Double, Double, String>> {
>     synchronized(this) {
> ```

What do you think of constructing the LRU as follows: 
  container = Collections.synchronizedMap(new LinkedHashMap<>());
and avoiding the synchronized blocks?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVouB_DtObDX9Mcx1N:-NXVouB_DtObDX9Mcx1O:b3pdobc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L71)):*
> ```Kotlin
>   }
> 
>   private fun calculateRanges(eventDay: Long): ArrayList<Triple<Double, Double, String>> {
> ```

@wliue can you take a look at this to make sure it's consistent with the way you want to handle rollouts?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVpQqx8SboAZQyUAbZ:-NXVpQqyEiNxKs_hCTq6:b8u1e1l) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L170)):*
> ```Kotlin
>   }
> 
>   private fun getEventFingerprint(labelerInput: LabelerInput): Long {
> ```

Can you refactor so that the labeller and this use the same code? https://sourcegraph.com/github.com/world-federation-of-advertisers/virtual-people-core-serving/-/blob/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt?L155


<!-- Sent from Reviewable.io -->

2023-06-15 06:43 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 21 of 23 files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxfec40_Q9Su8CSkP5:-NXxfec40_Q9Su8CSkP6:b-h2nxi7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L37)):*
> ```Kotlin
>   }
> 
>   private val lruCache: LRUCache<Long, ArrayList<Triple<Double, Double, String>>> =
> ```

Could add comment about the meaning of the Triple.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxf9Dw8yk5guRRGsbx:-NXxf9Dx85ujzmf4z669:bdq1pbv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L71)):*
> ```Kotlin
>   }
> 
>   private fun calculateRanges(eventDay: Long): ArrayList<Triple<Double, Double, String>> {
> ```

Could add a high-level description about the logic.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxfsJ81fwWE4_4nwVw:-NXxfsJ81fwWE4_4nwVx:b-e3xzr3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L78)):*
> ```Kotlin
>     val ranges = arrayListOf<Triple<Double, Double, String>>()
>     if (activeRollouts.size == 1) {
>       ranges.add(Triple(0.0, 1.1, activeRollouts.elementAt(0).modelRelease))
> ```

What is the meaning of these values? Maybe make them constants.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-NXxhpjOEkKOatOvnKMa:b-auqrqk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
> ```Kotlin
> 
>     val rolloutPeriodStartDay = (modelRollout.rolloutPeriod.startTime.seconds / 86_400L).toDouble()
>     val rolloutPeriodEndDay = (modelRollout.rolloutPeriod.endTime.seconds / 86_400L).toDouble()
> ```

Can start/end time be arbitrary number, or they need to be multiple of 86400, or (end - start) need to be multiple of 86400?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxlCtk54ZB8a3n6FPb:-NXxlCtk54ZB8a3n6FPc:b-534ekl) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L148)):*
> ```Kotlin
>         activeRollouts.add(rollout)
>         if (!rollout.hasRolloutFreezeTime()) {
>           // Stop only if there is no Freeze time set, otherwise we take one more rollout, if
> ```

Which code check it is one more rollout?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 170 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVpQqx8SboAZQyUAbZ:-NXxicPl-ys3Jj5pMoON:bszsn9k) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L170)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you refactor so that the labeller and this use the same code? https://sourcegraph.com/github.com/world-federation-of-advertisers/virtual-people-core-serving/-/blob/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt?L155
</blockquote></details>

They serve different purposes. In the labeler, we set the fingerprint for all user ids on the given event and the model will choose which id to use and set acting_fingerprint accordingly. This code chooses the first available user id using a fixed order. I think to reuse the code the best we can do is computing all fingerprints then choose in order.


<!-- Sent from Reviewable.io -->

2023-06-16 17:29 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 17 of 32 files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVnQki23RHyYPD0p73:-NY3UCecDJnqg7EOOXEy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt#L19)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you add a comment about what this is doing?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxfec40_Q9Su8CSkP5:-NY3b65X9SRxvycQPeYY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L37)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add comment about the meaning of the Triple.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo2rL9GL7HOkRb2ow:-NY47XQu72xU9KdKf3wx:b-vckhzk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should we be throwing an exception if we cannot find a model release?
</blockquote></details>

I'm not sure, is it an exception? I mean if there are no available ModelRelease(s) for the given event the function returns an empty list (which in my opinion is correct). The problem in that case would be that the ModelProvider didn't create rollouts / releases and so the whole system would be in an illegal state exception. Not sure this is the right place for that exception to be thrown and the EDP the one that receives that excepiton. 
What you think @kungfucraig ? 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo_NSCdfleP6C96dZ:-NY3roin40UGOMVz0o1w:bfym2op) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L60)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What do you think of constructing the LRU as follows: 
  container = Collections.synchronizedMap(new LinkedHashMap<>());
and avoiding the synchronized blocks?
</blockquote></details>

I did the change, even though I'm not entirely convinced that this approach works better. The synchronized block I had in place was to prevent multiple invocation of the ```calculateRanges(...)``` method.
Having a synchronized map ensures that the access to the object itself is synchronized and we do prevent race conditions, however when a read from the map fails, the ```lruCache.containsKey()``` method returns false, and we may (and will) end up having multiple threads entering the else block.

This was the reason of my approach @kungfucraig . Happly to apply your changes if we think that this won't translate in a bottleneck. 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxf9Dw8yk5guRRGsbx:-NY44uNz2P9_nW51RP09:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L71)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a high-level description about the logic.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxfsJ81fwWE4_4nwVw:-NY45GKt8Qz27hGbVew9:b-u0wbt6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L78)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

What is the meaning of these values? Maybe make them constants.
</blockquote></details>

I made them as constants. Each array of ranges (triples) spaces between 0.0 and 1.1.  Ranges are used to identify what model release must be returned for a given ```reducedEventId```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-NY45nHP7p4gtFBhcT_U:b-fd4xjq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Can start/end time be arbitrary number, or they need to be multiple of 86400, or (end - start) need to be multiple of 86400?
</blockquote></details>

start and end days cannot be arbitrary numbers. the rollout period is specified within the ModelRollout object (https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/model_rollout.proto#L45).

Since the adoption percentage of each model release is calculated on a daily basis, I do divide seconds by 86_400 (which are the seconds in one day) to calculate the day the event happens from epoch.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxlCtk54ZB8a3n6FPb:-NY4CWJoAOWJ7KUC9uVj:b-jjwgo7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L148)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Which code check it is one more rollout?
</blockquote></details>

The function iterates through all rollouts ordered by rollout_period_start_time, from the most recent one to the oldest.
The function keeps adding rollouts to the ```activeRollouts``` ArrayList unless some conditions are met:

1. ```eventDay >= rolloutPeriodEndDay && !rollout.hasRolloutFreezeTime()``` if the rollout has ```rolloutFreezeTime``` one more rollout (if present) is added
2. ```rolloutPeriodStartTime == rolloutPeriodEndTime``` in this case there is no gradual rollout and the current rollout is the last one we consider

If one of the above conditions is met, the for loop ```break``` and no other rollouts are considered ```active```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 170 at r1](https://reviewable.io/reviews/wor [...]

2023-06-19 17:59 UTC, kungfucraig requested changes
> Reviewed 10 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 27 of 32 files reviewed, 10 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo2rL9GL7HOkRb2ow:-NYJlMGH18AR4uppapWc:b-rlqir7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L56)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I'm not sure, is it an exception? I mean if there are no available ModelRelease(s) for the given event the function returns an empty list (which in my opinion is correct). The problem in that case would be that the ModelProvider didn't create rollouts / releases and so the whole system would be in an illegal state exception. Not sure this is the right place for that exception to be thrown and the EDP the one that receives that excepiton. 
What you think @kungfucraig ? 
</blockquote></details>

That's fair. The client of this function is probably in a better place to figure out what needs to be done if null is returned anyway.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo_NSCdfleP6C96dZ:-NYJltrE803pQp8ko1B-:b-5y83m6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L60)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I did the change, even though I'm not entirely convinced that this approach works better. The synchronized block I had in place was to prevent multiple invocation of the ```calculateRanges(...)``` method.
Having a synchronized map ensures that the access to the object itself is synchronized and we do prevent race conditions, however when a read from the map fails, the ```lruCache.containsKey()``` method returns false, and we may (and will) end up having multiple threads entering the else block.

This was the reason of my approach @kungfucraig . Happly to apply your changes if we think that this won't translate in a bottleneck. 
</blockquote></details>

Yeah, I can see what you mean. Multiple threads don't find the item, the all try to add it, but only one wins and the rest of them waste their time calculating something unnecessary. 

I just thought the synchronized block around access to the container was suspicious. Maybe put your old code back and add a comment in the code that echoes the above?


<!-- Sent from Reviewable.io -->

2023-06-20 07:29 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 26 of 32 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVnWGK6aIZeaujf6oV:-NYMdDyO586L7ngCT6oA:barqfjt) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L20)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@SanjayVas are we allowing import wildcards?
</blockquote></details>

I presume we are not, sorry! I changed that in the Labeler as well.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo2rL9GL7HOkRb2ow:-NYMb1AC8axjMi59Bl3y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

That's fair. The client of this function is probably in a better place to figure out what needs to be done if null is returned anyway.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXVo_NSCdfleP6C96dZ:-NYMdDEk4kQO4VaFhZGT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L60)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Yeah, I can see what you mean. Multiple threads don't find the item, the all try to add it, but only one wins and the rest of them waste their time calculating something unnecessary. 

I just thought the synchronized block around access to the container was suspicious. Maybe put your old code back and add a comment in the code that echoes the above?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-20 17:52 UTC, SanjayVas requested changes
First pass for Kotlin style.

> Reviewed 7 of 23 files at r1, 6 of 13 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-:-NYOvr6qBcYsbBLXzzaR:b-dcttcl)* status: 29 of 33 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/BUILD.bazel` line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOqlVO9H5TE8zyUDqE:-NYOqlVO9H5TE8zyUDqF:b-xwjlk7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/BUILD.bazel#L11)):*
> ```Starlark
>     srcs = glob(["*.kt"]),
>     deps = [
>         "@maven//:com_google_guava_guava",
> ```

All Maven deps should have aliases under the //imports tree based on the JVM package path. In this case, there's already an import alias in common-jvm.



_Suggestion:_
```Starlark
@wfa_common_jvm//imports/java/com/google/common:guava
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt` line 141 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOu5nd5HbSdvxU3vut:-NYOu5nd5HbSdvxU3vuu:b-up21jt) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt#L141)):*
> ```Kotlin
>       }
> 
>       /** root is guaranteed to be not null at this point. */
> ```

This comment shouldn't use KDoc syntax
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOuGbH8Pjs7lRMgMb8:-NYOuGbH8Pjs7lRMgMb9:b-imo9q0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L27)):*
> ```Kotlin
>  * The implementation of the CompiledNode with branch_node set.
>  *
>  * @param nodeConfig the compiledNode used to build the branch node. The field branch_node must be
> ```

Consider having a separate PR to first format all the files using the new version of ktfmt. Otherwise the blame results might be confusing.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOvJ0qBPTxH3l-D7dY:-NYOvJ0qBPTxH3l-D7dZ:b6vcobk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt#L17)):*
> ```Kotlin
> package org.wfanet.virtualpeople.core.selector
> 
> class LRUCache<K, V>(private val capacity: Int) : LinkedHashMap<K, V>(capacity) {
> ```

Follow [naming rules](https://developer.android.com/kotlin/style-guide#camel_case) from the style guide.



_Suggestion:_
```Kotlin
LruCache
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOv_DiAZFoSB3z08qi:-NYOv_Dj6o_BN0WnDzR8:b-plz8l9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt#L17)):*
> ```Kotlin
> package org.wfanet.virtualpeople.core.selector
> 
> class LRUCache<K, V>(private val capacity: Int) : LinkedHashMap<K, V>(capacity) {
> ```

All public types and members should be documented. See https://developer.android.com/kotlin/style-guide#usage
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOrilV2muQ8PSvMiyx:-NYOrilV2muQ8PSvMiyy:b-xrftny) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L26)):*
> ```Kotlin
>  * We need to convert it to ULong whenever we need to consume it, and convert it back to Long when
>  * we write back to proto.
>  */
> ```

The first line of a KDoc block should be a [summary fragment](https://developer.android.com/kotlin/style-guide#summary_fragment) describing the symbol. e.g. "Returns the FarmHash Fingerprint64 digest of [seed]."

As an aside, why is the argument called `seed`? This a hash function that can apply to any string input. It's not necessarily always going to be a seed, even if all current callers use it to hash a seed.



_Code quote:_
```Kotlin
/**
 * The fingerprint is expected to be a ULong, however, in Kotlin proto, uint64 is read/writen as
 * Long.
 *
 * We need to convert it to ULong whenever we need to consume it, and convert it back to Long when
 * we write back to proto.
 */
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOr5TbAgQP-CeZHqB-:-NYOr5TbAgQP-CeZHqB0:b-2bq4bk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
> ```Kotlin
>  * we write back to proto.
>  */
> fun getFingerprint64Long(seed: String): Long {
> ```

For new code we want to avoid having non-extension functions that aren't encapsulated by an object. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin

I'd recommend wrapping this in `object Hashing {}`
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOsqnz3EzBMgV_3noC:-NYOsqnz3EzBMgV_3noD:b-7vxxyu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
> ```Kotlin
>  * we write back to proto.
>  */
> fun getFingerprint64Long(seed: String): Long {
> ```

Match the naming used in org.wfanet.measurement.common.crypto. The base version should return a `ByteString`. The caller can use the `org.wfanet.measurement.common.toLong` extension on the result.



_Suggestion:_
```Kotlin
hashFingerprint64
```


<!-- Sent from Reviewable.io -->

2023-06-22 07:41 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 16 of 33 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/BUILD.bazel` line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOqlVO9H5TE8zyUDqE:-NYW_pYV0QKzqk6cpeUE:b32w1t) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/BUILD.bazel#L11)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All Maven deps should have aliases under the //imports tree based on the JVM package path. In this case, there's already an import alias in common-jvm.
</blockquote></details>

Ok
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt` line 141 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOu5nd5HbSdvxU3vut:-NYWlwdfAfF03YfI1Fvk:b-t1desy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comment shouldn't use KDoc syntax
</blockquote></details>

Ok, I also changed other comments in the same class that were not meant for KDoc IMO
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOrilV2muQ8PSvMiyx:-NYWd7jDCSYxLG_5-4h1:b-caq01a) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The first line of a KDoc block should be a [summary fragment](https://developer.android.com/kotlin/style-guide#summary_fragment) describing the symbol. e.g. "Returns the FarmHash Fingerprint64 digest of [seed]."

As an aside, why is the argument called `seed`? This a hash function that can apply to any string input. It's not necessarily always going to be a seed, even if all current callers use it to hash a seed.
</blockquote></details>

I'm not sure why it was used. Fair point, I changed it to ```input```. 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOr5TbAgQP-CeZHqB-:-NYWf_2uBKJUPgyNx9ah:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For new code we want to avoid having non-extension functions that aren't encapsulated by an object. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin

I'd recommend wrapping this in `object Hashing {}`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOsqnz3EzBMgV_3noC:-NYWlQOS52MWzFOIS4Lr:b-qqf6oy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Match the naming used in org.wfanet.measurement.common.crypto. The base version should return a `ByteString`. The caller can use the `org.wfanet.measurement.common.toLong` extension on the result.
</blockquote></details>

I changed the function name, however I noticed that the ```asLong()``` method provided by ```com.google.common.hash.HashCode``` returns a different value compare to:

```Hashing.farmHashFingerprint64().hashString(input, StandardCharsets.UTF_8).asBytes().toByteString().toLong()```

I'm not sure why, I guess it's because of the endianness used when interpreting bytes during conversions in the latter case.
This resulted in tests broken also in the Labeler class which doesn't make me confident do the change.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOvJ0qBPTxH3l-D7dY:-NYWmTyJ31AFu_QmAQ30:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow [naming rules](https://developer.android.com/kotlin/style-guide#camel_case) from the style guide.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOv_DiAZFoSB3z08qi:-NYWoA8W3e8WIDBuJXBm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LRUCache.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All public types and members should be documented. See https://developer.android.com/kotlin/style-guide#usage
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-22 18:18 UTC, SanjayVas requested changes
> Reviewed 2 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 18 of 33 files reviewed, 16 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOsqnz3EzBMgV_3noC:-NYZFirx5MJMucX-iubX:b5gj0ql) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I changed the function name, however I noticed that the ```asLong()``` method provided by ```com.google.common.hash.HashCode``` returns a different value compare to:

```Hashing.farmHashFingerprint64().hashString(input, StandardCharsets.UTF_8).asBytes().toByteString().toLong()```

I'm not sure why, I guess it's because of the endianness used when interpreting bytes during conversions in the latter case.
This resulted in tests broken also in the Labeler class which doesn't make me confident do the change.
</blockquote></details>

Ah yes, the `HashCode.asLong` documentation says it uses little endian where our `ByteString.toLong` extension uses big endian. We should document the endianness of the return value on this function.

Are we sure the Kotlin labeler implementation is generating the same fingerprint bytes in the proto message as the C++ implementation? My understanding is that the Java integers are big endian, meaning that the Java protobuf library will convert the endianness when serializing/deserializing integer fields.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYZHkbd807yjSxhdF3L:-NYZHkbd807yjSxhdF3M:broe8v7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L20)):*
> ```Kotlin
> import java.nio.charset.StandardCharsets
> 
> /**
> ```

This KDoc belongs on the method, not the wrapper object.


<!-- Sent from Reviewable.io -->

2023-06-22 19:51 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 18 of 33 files reviewed, 16 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOsqnz3EzBMgV_3noC:-NYZdJEOE-OaBg5h_Fys:ba63pox) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah yes, the `HashCode.asLong` documentation says it uses little endian where our `ByteString.toLong` extension uses big endian. We should document the endianness of the return value on this function.

Are we sure the Kotlin labeler implementation is generating the same fingerprint bytes in the proto message as the C++ implementation? My understanding is that the Java integers are big endian, meaning that the Java protobuf library will convert the endianness when serializing/deserializing integer fields.
</blockquote></details>

I think the tests are using the same input data, so we're probably okay on compatibility. We just should document what byte ordering this hash function uses. I'll create a seperate PR to allow specifying byte ordering in the existing functions in common-jvm so it's clearer there.


<!-- Sent from Reviewable.io -->

2023-06-22 21:41 UTC, kungfucraig approved these changes
Approved, but conditional on @wliue approving

> Reviewed 1 of 23 files at r1, 1 of 13 files at r2, 1 of 1 files at r4, 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-:-NY_2Wtp2HIvTQm8VFg1:b-g4zhoa)* status: all files reviewed, 11 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @wliue)



<!-- Sent from Reviewable.io -->

2023-06-26 00:53 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 17 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-NYozxLbEUOefD4Xd4w5:bpuwtbb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

start and end days cannot be arbitrary numbers. the rollout period is specified within the ModelRollout object (https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/model_rollout.proto#L45).

Since the adoption percentage of each model release is calculated on a daily basis, I do divide seconds by 86_400 (which are the seconds in one day) to calculate the day the event happens from epoch.


</blockquote></details>

Does that mean start/end time need to be multiple of 86400?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYozFf2-7rJ1so00_NM:-NYozFf2-7rJ1so00_NN:b-spvoy9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L126)):*
> ```Kotlin
>     } else {
>       val percentage: Double =
>         (eventDay - rolloutPeriodStartDay) / (rolloutPeriodEndDay - rolloutPeriodStartDay)
> ```

With this formula, percentage = 0 on rolloutPeriodStartDay. So the rollout starts one day later (and percentage = 1 on the day after rolloutPeriodEndDay). Is this the expected behavior? 



_Code quote:_
```Kotlin
      val percentage: Double =
        (eventDay - rolloutPeriodStartDay) / (rolloutPeriodEndDay - rolloutPeriodStartDay)
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxlCtk54ZB8a3n6FPb:-NYp0u3Z1C8nJyY5FL03:b-ipbybh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L148)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

The function iterates through all rollouts ordered by rollout_period_start_time, from the most recent one to the oldest.
The function keeps adding rollouts to the ```activeRollouts``` ArrayList unless some conditions are met:

1. ```eventDay >= rolloutPeriodEndDay && !rollout.hasRolloutFreezeTime()``` if the rollout has ```rolloutFreezeTime``` one more rollout (if present) is added
2. ```rolloutPeriodStartTime == rolloutPeriodEndTime``` in this case there is no gradual rollout and the current rollout is the last one we consider

If one of the above conditions is met, the for loop ```break``` and no other rollouts are considered ```active```
</blockquote></details>

So rather than "take one more rollout", it just continues, and there can be more than one rollouts added after this, correct?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYp4f1b7ZpVHniinhnx:-NYp4f1b7ZpVHniinhny:bmru0q5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L163)):*
> ```Kotlin
>         ) {
>           // No gradual rollout. The rollout immediately labels 100% of events
>           break
> ```

Is this code reachable?
rollout start = end, and eventDay >= rollout start, so eventDay >= rollout end, therefore it enters if block at the beginning, and either break or continue.



_Code quote:_
```Kotlin
          // No gradual rollout. The rollout immediately labels 100% of events
          break
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 248 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYp5cmb40-wY8T2Cv9m:-NYp5cmb40-wY8T2Cv9n:b-hpsc5a) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L248)):*
> ```Kotlin
>       return getFingerprint64Long(labelerInput.eventId.id)
>     }
>     return (0..Long.MAX_VALUE).random()
> ```

Should we raise an error here?



_Code quote:_
```Kotlin
    return (0..Long.MAX_VALUE).random()
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYohcsQ-LphdZTS84Nd:-NYohcsQ-LphdZTS84Ne:b-r7xzd4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L31)):*
> ```Kotlin
> 
>   init {
>     val modelLineId = modelLine.name.split("/").drop(5).take(1).toString()
> ```

Could add comment about drop(5).



_Code quote:_
```Kotlin
drop(5)
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 33 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYoi0SK1v0xhYqjIM4i:-NYoi0SK1v0xhYqjIM4j:b-1hgyty) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L33)):*
> ```Kotlin
>     val modelLineId = modelLine.name.split("/").drop(5).take(1).toString()
>     for (rollout in rollouts) {
>       val modelRolloutId = rollout.name.split("/").drop(5).take(1).toString()
> ```

This is the modelLineId in the path of the modelRollout, correct? Rename it accordingly.



_Code quote:_
```Kotlin
modelRolloutId
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYojF6V9MhnQeW6ihoh:-NYojF6W73fe3Pe9MNV2:blt8011) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L46)):*
> ```Kotlin
>    *
>    * E.g. [<0.0,0.5,ModelRelease1>,<0.5,1.1,ModelRelease2>] means that if the reducedEventId is
>    * lower than 0.5, ModelRelease1 is returned, ModelRelease2 otherwise.
> ```

Could add comment whether the lower bound and the upper bound are inclusive.



_Code quote:_
```Kotlin
   * E.g. [<0.0,0.5,ModelRelease1>,<0.5,1.1,ModelRelease2>] means that if the reducedEventId is
   * lower than 0.5, ModelRelease1 is returned, ModelRelease2 otherwise.
```


<!-- Sent from Reviewable.io -->

2023-06-26 12:27 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 27 of 33 files reviewed, 17 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-NYr-oPJ8pdNcwe7-lTk:bnk2x2s) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Does that mean start/end time need to be multiple of 86400?
</blockquote></details>

No they don't need to be multiple of 86400. They can have any value.
```rolloutPeriodStartDay``` and ```rolloutPeriodEndDay``` are divided by 86_400L. The division of 2 Long numbers return a Long number which is then converted to DOUBLE (e.g. 1234567L --> 1234567.0).
The conversion to DOUBLE and so the decimal part that is appended ```.0``` is needed when calculating the ```percentage```, otherwise it would always be == 0 if Long numbers were used.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYozFf2-7rJ1so00_NM:-NYr1sPO7yxE5f4T5wcq:b-rqruf8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L126)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

With this formula, percentage = 0 on rolloutPeriodStartDay. So the rollout starts one day later (and percentage = 1 on the day after rolloutPeriodEndDay). Is this the expected behavior? 
</blockquote></details>

Yes it is expected indeed.
For instance if we have a rollout that spans across 5 days (10..15), the percentage would be like this:

day 10 (day 0 of rollout) -> 0%
day 11 (day 1 of rollout) -> 20%
day 12 (day 2 of rollout) -> 40%
day 13 (day 3 of rollout) -> 60%
day 14 (day 4 of rollout) --> 80%
day 15 (day 5 of rollout) -->100%

I've done it like this since ```rollotPeriodStartTime.seconds``` can represent any moment in that day (e.g. 10pm). And so the new rollout shouldn't take place until that moment. I.e. `rolloutPeriodStartTime``` is day 0. The following day is day 1 and events begin to be labeled.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxlCtk54ZB8a3n6FPb:-NYr5X8eChvsNwo9XxJf:b-wg4yyw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L148)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

So rather than "take one more rollout", it just continues, and there can be more than one rollouts added after this, correct?
</blockquote></details>

That's correct. If ```eventDay >= rolloutPeriodEndDay```, it keeps adding rollouts until it finds one without rollout_freeze_time or there are no more rollouts to add.
I've updated the comment.

On the other hand if ```rolloutPeriodStartTime === rolloutPeriodEndTime``` there is no gradual rollout (and so there cannot be any ```rollout_freeze_time```); meaning the for loop break and doesn't add any other rollouts.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYp4f1b7ZpVHniinhnx:-NYr8RxP0verktpG1qI8:b-aao4qp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L163)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is this code reachable?
rollout start = end, and eventDay >= rollout start, so eventDay >= rollout end, therefore it enters if block at the beginning, and either break or continue.
</blockquote></details>

That's true. I've removed that block
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 248 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYp5cmb40-wY8T2Cv9m:-NYr8h8N7D7jEDczfVSR:bkzykmc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L248)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Should we raise an error here?
</blockquote></details>

That's a good point. So a requirement for the selector would be that the EDP always provides at least one identifier. I've update the code to throw an error in that case
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYohcsQ-LphdZTS84Nd:-NYqy4Z76bZ5aQDYobrA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L31)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add comment about drop(5).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 33 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYoi0SK1v0xhYqjIM4i:-NYqyKNl75_Dpi8grw9b:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L33)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

This is the modelLineId in the path of the modelRollout, correct? Rename it accordingly.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYojF6V9MhnQeW6ihoh:-NYqyifF-M2_Tg1cmA0h:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L46)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add comment whether the lower bound and the upper bound are inclusive.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYOsqnz3EzBMgV_3noC:-NYrevtTAVj1N-tHTXFl:btjfiow) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9a78c817bdb914bb9f00c9fe71cc8509b6a53163/src/main/kotlin/org/wfanet/virtualpeople/core/common/Hashing.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the tests are using the same input data, so we're probably okay on compatibility. We just should document what byte ordering this hash function uses. I [...]

2023-06-26 17:33 UTC, EvgSkv commented on src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt
> +  private fun calculateRanges(eventDay: Long): ArrayList<Triple<Double, Double, String>> {
To me this code seems to be different than what we have converged on during the meetings.
The sequential roll-out that (I thought) we agreed upon would look like this pseudocode:
```
use_model = first known rollout
for each rollout ordered by start time:
  let percentage = (current time - rollout start) / (rollout end - rollout start)
  let fingerprint = Hash(Concatenate(rollout id, event fingerprint))
  if fingerprint < percentage:
    use_model = this rollout
```
While this implementation seems to be following a different algorithm.

2023-06-26 17:54 UTC, wliue commented
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 109 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#gh-1242529210:-NYsoge2BidUkmejch6c:b-g9laee) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/16162f3ed565df3e9e51f768919206b62f8bb828/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L109)):*
<details><summary><i>Previously, EvgSkv (Evgeny Skvortsov) wrote…</i></summary><blockquote>

To me this code seems to be different than what we have converged on during the meetings.
The sequential roll-out that (I thought) we agreed upon would look like this pseudocode:
```
use_model = first known rollout
for each rollout ordered by start time:
  let percentage = (current time - rollout start) / (rollout end - rollout start)
  let fingerprint = Hash(Concatenate(rollout id, event fingerprint))
  if fingerprint < percentage:
    use_model = this rollout
```
While this implementation seems to be following a different algorithm.


</blockquote></details>

Also want to point out that, with the current impl, it seems to me every user id(assuming it has daily activity) will be be labeled by all the models at some point. In particular, even if a model is frozen, it will expand to label event with new user ids. 


<!-- Sent from Reviewable.io -->

2023-06-27 11:45 UTC, Marco-Premier commented
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 109 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#gh-1242529210:-NYwSACo3jz5QYSwgQRH:b-jw3gve) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/16162f3ed565df3e9e51f768919206b62f8bb828/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L109)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Also want to point out that, with the current impl, it seems to me every user id(assuming it has daily activity) will be be labeled by all the models at some point. In particular, even if a model is frozen, it will expand to label event with new user ids. 
</blockquote></details>

Hi @EvgSkv , I think there's one problem with your pseudo code.
If we are in the middle of let's say 2 rollouts, and each one take 50% of events, if a fingerprint if 0.8, none of them is going to be chosen but rather the 'first_known_rollout' which may be entitle to label 0% of events.

What I do is to create a snapshot of the penetration of each model for a given day and cache it. Once that's done, to retrieve the  correct model for that day I basically do the same:

```
for (triple in ranges) {
    if (reducedEventId < triple.second) { 
      return triple.third
    }
}
```

An example of ```ranges``` for day X would be:
- range 1 = [0.0, 0.12, model 1]  //12% with model 1
- range 2 = [0.12, 0.68, model 2]  // 56% with model 2
- range 3 = [0.68, 1.1, model 3]  // 32% with model 3

day X+1 for instance would be:
- range 1 = [0.0, 0.15, model 1]  // 15% with model 1
- range 2 = [0.15, 0.70, model 2] // 55% with model 2
- range 3 = [0.70, 1.1, model 3]  // 30% with model 3

And so if the user_id fingerprint is, let's say 0.9, it will be labelled with model 3, then after some time with model 2 and finally with model 1 that takes 100% of events. That is, it ensures that for a certain period of time, the same event fingerprint is constantly labelled with the same model, and every day just a fixed % of events is labelled with a given model.

The idea of caching models penetration each day was to make the function faster. By doing so:
- old rollouts (which are not used) are not considered
- the HASH is calculated only once
- the percentage is cached and doesn't need to be calculated over and over for every couple of event / rollout

Does it make sense to you? isn't this the desired output?

thank you


<!-- Sent from Reviewable.io -->

2023-06-27 11:54 UTC, Marco-Premier commented
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 109 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#gh-1242529210:-NYwf2W644Up8lbQvHl0:b-nidxqu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/16162f3ed565df3e9e51f768919206b62f8bb828/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L109)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Hi @EvgSkv , I think there's one problem with your pseudo code.
If we are in the middle of let's say 2 rollouts, and each one take 50% of events, if a fingerprint if 0.8, none of them is going to be chosen but rather the 'first_known_rollout' which may be entitle to label 0% of events.

What I do is to create a snapshot of the penetration of each model for a given day and cache it. Once that's done, to retrieve the  correct model for that day I basically do the same:

```
for (triple in ranges) {
    if (reducedEventId < triple.second) { 
      return triple.third
    }
}
```

An example of ```ranges``` for day X would be:
- range 1 = [0.0, 0.12, model 1]  //12% with model 1
- range 2 = [0.12, 0.68, model 2]  // 56% with model 2
- range 3 = [0.68, 1.1, model 3]  // 32% with model 3

day X+1 for instance would be:
- range 1 = [0.0, 0.15, model 1]  // 15% with model 1
- range 2 = [0.15, 0.70, model 2] // 55% with model 2
- range 3 = [0.70, 1.1, model 3]  // 30% with model 3

And so if the user_id fingerprint is, let's say 0.9, it will be labelled with model 3, then after some time with model 2 and finally with model 1 that takes 100% of events. That is, it ensures that for a certain period of time, the same event fingerprint is constantly labelled with the same model, and every day just a fixed % of events is labelled with a given model.

The idea of caching models penetration each day was to make the function faster. By doing so:
- old rollouts (which are not used) are not considered
- the HASH is calculated only once
- the percentage is cached and doesn't need to be calculated over and over for every couple of event / rollout

Does it make sense to you? isn't this the desired output?

thank you
</blockquote></details>

@wliue  I'm not sure I follow the part with frozen models.

```
val percentage: Double =
        (modelRolloutFreezeTimeDay - rolloutPeriodStartDay) /
          (rolloutPeriodEndDay - rolloutPeriodStartDay)
```

If the rollout starts its rollout at day 10, end day is 20 and freeze time is 15: at day 15, 50% of events will be labelled with that model. However from day 16 on, the above snippet, blocks the percentage to 50%, so all the events that generate a fingerprint greater than 0.5 will never use that model.

So, yes, it's true that new event_ids can be potentially labelled with the model with freeze time, however we won't have more than (in the above case) 50% of daily events labelled with that model (some event_ids will never use it).

During our meetings we agreed that a model rollout with freeze time set, should be followed by a new model rollout that takes over and gradually (or instantly) replaces the rollout with freeze time.


<!-- Sent from Reviewable.io -->

2023-06-27 18:38 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 27 of 33 files reviewed, 18 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 248 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYp5cmb40-wY8T2Cv9m:-NYy72VwCVRJ2N_A3Jid:b-sek8b9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L248)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

That's a good point. So a requirement for the selector would be that the EDP always provides at least one identifier. I've update the code to throw an error in that case
</blockquote></details>

Could also mention that the event_id is not set either.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 109 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#gh-1242529210:-NYy7bWP4KwZ3GjlK7aF:beuki0m) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/16162f3ed565df3e9e51f768919206b62f8bb828/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L109)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

@wliue  I'm not sure I follow the part with frozen models.

```
val percentage: Double =
        (modelRolloutFreezeTimeDay - rolloutPeriodStartDay) /
          (rolloutPeriodEndDay - rolloutPeriodStartDay)
```

If the rollout starts its rollout at day 10, end day is 20 and freeze time is 15: at day 15, 50% of events will be labelled with that model. However from day 16 on, the above snippet, blocks the percentage to 50%, so all the events that generate a fingerprint greater than 0.5 will never use that model.

So, yes, it's true that new event_ids can be potentially labelled with the model with freeze time, however we won't have more than (in the above case) 50% of daily events labelled with that model (some event_ids will never use it).

During our meetings we agreed that a model rollout with freeze time set, should be followed by a new model rollout that takes over and gradually (or instantly) replaces the rollout with freeze time.

</blockquote></details>

@Marco-Premier The frozen model is not just labeling new events, it labels events whose user_id is not labeled by this model before the freeze. I think that defeats the purpose of freeze.


<!-- Sent from Reviewable.io -->

2023-06-28 09:22 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 27 of 33 files reviewed, 18 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 248 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYp5cmb40-wY8T2Cv9m:-NZ0IBCQDpy1AhR0i9pW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L248)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could also mention that the event_id is not set either.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-30 19:42 UTC, wliue approved these changes
> Reviewed 15 of 23 files at r1, 1 of 13 files at r2, 1 of 1 files at r4, 10 of 15 files at r5, 4 of 6 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 21 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 76 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCfy5zDuk-MHba7NTH:-NZCfy5zDuk-MHba7NTI:bivogjb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L76)):*
> ```Kotlin
>               buildString {
>                 append(percentage.second)
>                 append(getEventId(labelerInput))
> ```

Only need to compute getEventId(labelerInput) once.



_Code quote:_
```Kotlin
getEventId(labelerInput)
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 358 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCnrR8DYng99Wd9ioH:-NZCnrR8DYng99Wd9ioI:b3v73wt) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L358)):*
> ```Kotlin
> 
>   @Test
>   fun `getModelRelease returns correct ModelRelease with three rollouts (R1 & R2 & R3) and reducedEventId is smaller than R1 and R2`() {
> ```

Could add a case that reduced id is smaller than R1, higher than R2, and smaller than R3.



_Code quote:_
```Kotlin
 fun `getModelRelease returns correct ModelRelease with three rollouts (R1 & R2 & R3) and reducedEventId is smaller than R1 and R2`() {
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCboYG50ASCxWVyNXO:-NZCboYG50ASCxWVyNXP:b21pjqs) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt#L21)):*
> ```Kotlin
>  * been accessed or used for the longest are evicted first when the cache is full.
>  */
> class LruCache<K, V>(private val capacity: Int) : LinkedHashMap<K, V>(capacity) {
> ```

Is this java.util.LinkedHashMap or kotlin.collections.LinkedHashMap?
Should we specify accessOrder here?
https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html#LinkedHashMap-int-



_Code quote:_
```Kotlin
class LruCache<K, V>(private val capacity: Int) : LinkedHashMap<K, V>(capacity) 
```


<!-- Sent from Reviewable.io -->

2023-06-30 19:51 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 21 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCboYG50ASCxWVyNXO:-NZCquKD0UIza0XYXFCL:b-6v7ioj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt#L21)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is this java.util.LinkedHashMap or kotlin.collections.LinkedHashMap?
Should we specify accessOrder here?
https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html#LinkedHashMap-int-
</blockquote></details>

`kotlin.collections.LinkedHashMap` is an alias for `java.util.LinkedHashMap` when using Kotlin JVM.


<!-- Sent from Reviewable.io -->

2023-06-30 19:58 UTC, wliue approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 21 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-NZCs7Rx5UQ6snHlxT0a:bxsx0z4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

No they don't need to be multiple of 86400. They can have any value.
```rolloutPeriodStartDay``` and ```rolloutPeriodEndDay``` are divided by 86_400L. The division of 2 Long numbers return a Long number which is then converted to DOUBLE (e.g. 1234567L --> 1234567.0).
The conversion to DOUBLE and so the decimal part that is appended ```.0``` is needed when calculating the ```percentage```, otherwise it would always be == 0 if Long numbers were used.
</blockquote></details>

@EvgSkv What is your opinion regarding align the start/end with day?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYozFf2-7rJ1so00_NM:-NZCsSCP8QMVJMaaSHUL:b9hr1i9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L126)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Yes it is expected indeed.
For instance if we have a rollout that spans across 5 days (10..15), the percentage would be like this:

day 10 (day 0 of rollout) -> 0%
day 11 (day 1 of rollout) -> 20%
day 12 (day 2 of rollout) -> 40%
day 13 (day 3 of rollout) -> 60%
day 14 (day 4 of rollout) --> 80%
day 15 (day 5 of rollout) -->100%

I've done it like this since ```rollotPeriodStartTime.seconds``` can represent any moment in that day (e.g. 10pm). And so the new rollout shouldn't take place until that moment. I.e. `rolloutPeriodStartTime``` is day 0. The following day is day 1 and events begin to be labeled.

</blockquote></details>

@EvgSkv This is related to the comment above. Should we align start/end time to day to avoid confusion?


<!-- Sent from Reviewable.io -->

2023-07-06 18:16 UTC, EvgSkv commented
I share Wei's concerns about start and end not being aligned with start and end of dates. But we can discuss this separately and have another PR if needed. Other than that looks great! Thank you!

2023-07-06 18:18 UTC, EvgSkv approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-:-NZgQGEh-tPre5VAPqxj:bnfp4nl)* status: all files reviewed, 21 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-08 02:13 UTC, stevenwarejones reviewed
> Reviewed 18 of 23 files at r1, 1 of 1 files at r4, 2 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 24 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, and @wliue)

___
*[`build/repositories.bzl` line 45 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZnGN7uAWNUeGPKaf_C:-NZnGN7uAWNUeGPKaf_D:b2bxi56) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/build/repositories.bzl#L45)):*
> ```Starlark
> 
>     http_archive(
>         name = "wfa_measurement_proto",
> ```

we're okay with having this repo depend on the public api? @SanjayVas 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXRggbeCd1MBA46C2XO:-NXRggbeCd1MBA46C2XP:b3kre) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt#L144)):*
> ```Kotlin
>      * when we write back to proto.
>      */
>     /*private fun getFingerprint64Long(seed: String): Long {
> ```

?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXRgb1j60NkfylbPMH9:-NXRgb1k2oPxoWKADR3H:b-l4715s) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt#L27)):*
> ```Kotlin
>  * we write back to proto.
>  */
> fun getFingerprint64Long(seed: String): Long {
> ```

this should be in common-jvm (if its not there already)


<!-- Sent from Reviewable.io -->

2023-07-10 20:03 UTC, stevenwarejones reviewed
> Reviewed 1 of 15 files at r5, 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 18 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-10 20:36 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 22 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-N_0PWnn-yzTkszXHzEv:b-a8yna) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

@EvgSkv What is your opinion regarding align the start/end with day?
</blockquote></details>

I also don't think they need to be multiples of 86400. What's the motivation for needing releases to perfectly align with UTC?

I do think that since this reference implementation uses a cache based on UTC day, it might be a best practice to have the roll outs align with UTC days but I don't think its a hard requirement, right?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYohcsQ-LphdZTS84Nd:-N_0SDitESUuOnw4gUc9:b-m7g31w) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L31)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd prefer you re-implement ModelLineKey from cross-media-measurement for parsing - wdyt @SanjayVas ?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 39 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0Sb_R7GevqxUihe0R:-N_0Sb_R7GevqxUihe0S:b-l07r6w) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L39)):*
> ```Kotlin
>     val modelLineId = modelLine.name.split("/").drop(5).take(1).toString()
>     for (rollout in rollouts) {
>       val modelRolloutModelLineId = rollout.name.split("/").drop(5).take(1).toString()
> ```

ditto on implementing the ResourceKey parser
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0T-cw75jlmBTP2miv:-N_0T-cw75jlmBTP2miw:b6d89pf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L54)):*
> ```Kotlin
>    * most recent.
>    */
>   private val lruCache: LruCache<Long, ArrayList<Pair<Double, String>>> = LruCache(CACHE_SIZE)
> ```

can you comment that this is a UTC based cache?
Also, I think .... `LruCache<UInt` should be more than sufficient. (11 million years coverage)
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 118 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0QRMJ0AISIyNmcqLO:-N_0QRMJ0AISIyNmcqLP:b-7wpti) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L118)):*
> ```Kotlin
>    * (ROLLOUT_END_DAY - ROLLOUT_START_DAY)
>    */
>   private fun calculatePercentages(eventDay: Long): ArrayList<Pair<Double, String>> {
> ```

can you use a more meaningful data type
```
private class ModelReleasePercentile(
  endPercentile: Double,
  modelReleaseResourceKey: String,
)
   
private fun calculatePercentages(eventDay: Long): ArrayList<ModelReleasePercentile<Double, String>> {
```

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 135 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0R6UwBKrd5QiqYfaH:-N_0R6UwBKrd5QiqYfaI:b-ble6nu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L135)):*
> ```Kotlin
>     val modelRolloutFreezeTimeDay =
>       if (modelRollout.hasRolloutFreezeTime()) {
>         modelRollout.rolloutFreezeTime.seconds / 86_400L
> ```

can you make 86_400L a constant everywhere


<!-- Sent from Reviewable.io -->

2023-07-10 21:44 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 22 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYohcsQ-LphdZTS84Nd:-N_0ikDS08WZSERv93W5:b-dnkzib) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer you re-implement ModelLineKey from cross-media-measurement for parsing - wdyt @SanjayVas ?
</blockquote></details>

It need not be the same `ResourceKey` types as long as it's clear what's happening here, and ensuring that if you have similar parsing logic in multiple places that it's factored out.

e.g. if it's just the simple case of grabbing the last segment, `split("/").last()` is fine IMO. If trying to grab other segments, you may want something more structured.


<!-- Sent from Reviewable.io -->

2023-07-11 16:07 UTC, stevenwarejones reviewed
> Reviewed 1 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 22 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-11 18:50 UTC, wliue approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 22 unresolved discussions (waiting on @EvgSkv and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-N_5Fd9-3JVGVdq90ODF:b-wvme7x) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I also don't think they need to be multiples of 86400. What's the motivation for needing releases to perfectly align with UTC?

I do think that since this reference implementation uses a cache based on UTC day, it might be a best practice to have the roll outs align with UTC days but I don't think its a hard requirement, right?
</blockquote></details>

There is no fundamental requirement that it need to align with UTC. But because the rollout percentage computation is based on UTC, and the adoption percentage is by day, it makes more sense to align with that to avoid confusion. For example, someone can schedule rollout A that start at 01/01 5pm and end at 01/30 3am, then schedule rollout B start at 01/10 7am, end at 02/10 1am. It is not intuitive to tell exactly when the rollout would happen, and the behavior may not be what the user expected.


<!-- Sent from Reviewable.io -->

2023-07-11 21:23 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 22 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-N_5ovwO1rRJH2WNk1Ng:bxsdgbl) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
> the adoption percentage is by day

We've avoided any relation to calendar days (UTC or otherwise) in the rollout API definition, intentionally allowing arbitrary timestamps.


<!-- Sent from Reviewable.io -->

2023-07-14 19:57 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 21 unresolved discussions (waiting on @EvgSkv, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXRggbeCd1MBA46C2XO:-N_Ks0b7Di7kaXuDHxJm:biu30m3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/Labeler.kt#L144)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

?
</blockquote></details>

This has been moved under common package in order to reuse it within the Selector
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYozFf2-7rJ1so00_NM:-N_J2ILH7n1KPF7CX5h9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L126)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

@EvgSkv This is related to the comment above. Should we align start/end time to day to avoid confusion?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NYohcsQ-LphdZTS84Nd:-N_KqaHX9DYLXl2iMXXA:b-6gb5m7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/39f1ad80f45a991fe3a7edb65f859d78dea9d785/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It need not be the same `ResourceKey` types as long as it's clear what's happening here, and ensuring that if you have similar parsing logic in multiple places that it's factored out.

e.g. if it's just the simple case of grabbing the last segment, `split("/").last()` is fine IMO. If trying to grab other segments, you may want something more structured.
</blockquote></details>

@stevenwarejones I provided a simplified version of parser we have in cross-media-measurement to make it clearer what ids we are using. I think that importing whole the classes we use in XMM repo is a bit overkilling and harder to maintain for this fairly simple use case
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 39 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0Sb_R7GevqxUihe0R:-N_KqocN6M7ejX_IXX6C:bxxos8z) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on implementing the ResourceKey parser
</blockquote></details>

same as above comment
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0T-cw75jlmBTP2miv:-N_Kayyw1CpktYaeRuvx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you comment that this is a UTC based cache?
Also, I think .... `LruCache<UInt` should be more than sufficient. (11 million years coverage)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 76 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCfy5zDuk-MHba7NTH:-N_JAOXTAclJV5wXy6AR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L76)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Only need to compute getEventId(labelerInput) once.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 118 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0QRMJ0AISIyNmcqLO:-N_J9Zo03HMD00VVT3io:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L118)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you use a more meaningful data type
```
private class ModelReleasePercentile(
  endPercentile: Double,
  modelReleaseResourceKey: String,
)
   
private fun calculatePercentages(eventDay: Long): ArrayList<ModelReleasePercentile<Double, String>> {
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 135 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_0R6UwBKrd5QiqYfaH:-N_J4oDdEoS4RoZlC-zY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L135)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make 86_400L a constant everywhere
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 44 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_-LgSoAoj2-2Pjnczp:-N_J3PyW5bOEJ_tDCpeu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`getDefaultInstance` is preferred as it will return a singleton rather than potentially creating a new instance each time
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 358 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCnrR8DYng99Wd9ioH:-N_Kx52a0LagOubWXhlJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L358)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a case that reduced id is smaller than R1, higher than R2, and smaller than R3.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXRgb1j60NkfylbPMH9:-N_Ky9W5BBW5bc-5LgPs:bwiwi5a) ([raw file](https://github.com/world-federation-of-advertisers/virtua [...]

2023-07-14 20:33 UTC, wliue approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 21 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCboYG50ASCxWVyNXO:-N_L4ocQ32Crx-my90of:b1u3zya) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`kotlin.collections.LinkedHashMap` is an alias for `java.util.LinkedHashMap` when using Kotlin JVM.
</blockquote></details>

@Marco-Premier Seems that we need to specify accessOrder = true, otherwise it default to insertion-order.


<!-- Sent from Reviewable.io -->

2023-07-20 18:13 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 25 of 36 files reviewed, 17 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NZCboYG50ASCxWVyNXO:-N_oVT_W1cSczVwD0-LE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/54c333efbddaf09fa155013632fd7983f5a8bbd1/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt#L21)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

@Marco-Premier Seems that we need to specify accessOrder = true, otherwise it default to insertion-order.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-21 18:22 UTC, stevenwarejones approved these changes
> Reviewed 1 of 23 files at r1, 1 of 13 files at r2, 8 of 15 files at r5, 4 of 6 files at r9, 11 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 18 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 309 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-N_tfmmk6nnciSJnNMLW:-N_tfmmk6nnciSJnNMLX:b-lghfnf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e77ebe9f7915220d1a8d491c6e5d0d7ae853011b/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L309)):*
> ```Kotlin
> 
>   private fun daysFromEpoch(date: Date): Long {
>     val epochDate = LocalDate.of(1970, 1, 1)
> ```

nit: this can be a private class variable
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXRgb1j60NkfylbPMH9:-N_tfF77EHwIm_ocabyh:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt#L27)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

is it reasonable to do this change in a separate PR?
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2023-07-25 13:26 UTC, Marco-Premier reviewed
Hi @SanjayVas I see you are still blocking this PR. Could you please have another pass? thanks

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-:-NaCDdZQ9wddRhaEsnjk:bq7eyy6)* status: 33 of 36 files reviewed, 17 unresolved discussions (waiting on @EvgSkv, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXRgb1j60NkfylbPMH9:-NaCC_CP349o-SjuifnH:bhnbg3u) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/common/HashFarm.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sure
</blockquote></details>

added a TODO


<!-- Sent from Reviewable.io -->

2023-07-25 20:31 UTC, SanjayVas requested changes
Sorry, I hadn't realized.

> Reviewed 3 of 23 files at r1, 7 of 15 files at r5, 4 of 6 files at r9, 9 of 11 files at r10, 2 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-:-NaDUYkyBQyQC35mrEk7:b-60g63x)* status: 35 of 36 files reviewed, 22 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/BUILD.bazel` line 81 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDjeLeBbegC1QZOREh:-NaDjeLeBbegC1QZOREi:b-smh7f) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/main/kotlin/org/wfanet/virtualpeople/core/selector/BUILD.bazel#L81)):*
> ```Starlark
> )
> 
> kt_jvm_proto_library(
> ```

This target already exists in common-jvm as`@wfa_common_jvm//src/main/proto/google/type:date_kt_jvm_proto`.

Even if you were to define it in this repo, it goes in Bazel package that it would were the proto_library defined in this repo.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/resourcekey/ModelRolloutKey.kt` line 17 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDV6YnAQPxDL1amMVQ:-NaDV6YnAQPxDL1amMVR:undefined) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/main/kotlin/org/wfanet/virtualpeople/core/selector/resourcekey/ModelRolloutKey.kt#L17)):*
> ```Kotlin
>  */
> 
> package org.wfanet.measurement.api.v2alpha
> ```





_Suggestion:_
```Kotlin
package org.wfanet.virtualpeople.core.selector.resourcekey
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 41 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDVRoZ4KhOea1YH0NM:-NaDVRoZ4KhOea1YH0NN:bz43evb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L41)):*
> ```Kotlin
>     val modelLine =
>       parseTextProto(
>         File("$TEXTPROTO_PATH/model_line_02.textproto").bufferedReader(),
> ```

Use the overload that takes in a `File`. It manages the reader for you, guaranteeing it gets closed.



_Code quote:_
```Kotlin
.bufferedReader()
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 55 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDWXR8BQ-UEo1VZ7TV:-NaDWXR8BQ-UEo1VZ7TW:b-iof0xy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L55)):*
> ```Kotlin
>       }
> 
>     assertEquals(exception.message, "ModelRollouts must be parented by the provided ModelLine.")
> ```

Avoid asserting on exact exception message text, as the implementation should have flexibility to change them. Generally asserting on the message is only done to

1. Disambiguate between multiple causes of the same exception type
2. Verify that the exception message contains enough information

The above can be accomplished by checking that the message contains some text rather than that the whole message exactly matches some text. Note that you should be using Truth for all assertions except where noted in the style guide. There's also a specific Truth subject for exceptions.



_Suggestion:_
```Kotlin
assertThat(exception).hasMessageThat().contains("parented")
```
___
*[`src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel` line 1 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDX8F93qEF3QnyVcTe:-NaDX8F93qEF3QnyVcTf:b-7c3ye) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel#L1)):*
> ```Starlark
> package(default_visibility = [
> ```

These targets should be under a `testing` package in the `src/main` tree, with `default_testonly = True`. e.g. `//src/main/kotlin/org/wfanet/virtualpeople/core/selector/testing/testdata`
___
*[`src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel` line 7 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDWzarAbqjwqy_K50r:-NaDWzarAbqjwqy_K50s:b-2y506o) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel#L7)):*
> ```Starlark
> exports_files(
>     glob(["*.textproto"]),
> )
> ```

Why do you need this?



_Code quote:_
```Starlark
exports_files(
    glob(["*.textproto"]),
)
```


<!-- Sent from Reviewable.io -->

2023-07-26 09:46 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 19 of 38 files reviewed, 21 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/BUILD.bazel` line 81 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDjeLeBbegC1QZOREh:-NaGQaNkCuKw0Q_ze0Ar:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/main/kotlin/org/wfanet/virtualpeople/core/selector/BUILD.bazel#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This target already exists in common-jvm as`@wfa_common_jvm//src/main/proto/google/type:date_kt_jvm_proto`.

Even if you were to define it in this repo, it goes in Bazel package that it would were the proto_library defined in this repo.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 117 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NXxhpjOEkKOatOvnKM_:-NaGQd__0gDCqM2dMyDS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0309c6c62b11ea7af6faf09223eca8ca765e0caf/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L117)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas - Yes - but this reference implementation only allows adoption percentage to align with UTC 
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/resourcekey/ModelRolloutKey.kt` line 17 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDV6YnAQPxDL1amMVQ:-NaGSvryA7rXMZEXB8Lk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/main/kotlin/org/wfanet/virtualpeople/core/selector/resourcekey/ModelRolloutKey.kt#L17)):*
> ```Kotlin
>  */
> 
> package org.wfanet.measurement.api.v2alpha
> ```

Done.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 41 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDVRoZ4KhOea1YH0NM:-NaGV1r45kwTfvYfO8vf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the overload that takes in a `File`. It manages the reader for you, guaranteeing it gets closed.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt` line 55 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDWXR8BQ-UEo1VZ7TV:-NaGWtTF2CfXdYLlJsb_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelectorTest.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Avoid asserting on exact exception message text, as the implementation should have flexibility to change them. Generally asserting on the message is only done to

1. Disambiguate between multiple causes of the same exception type
2. Verify that the exception message contains enough information

The above can be accomplished by checking that the message contains some text rather than that the whole message exactly matches some text. Note that you should be using Truth for all assertions except where noted in the style guide. There's also a specific Truth subject for exceptions.
</blockquote></details>

Done.
___
*[`src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel` line 1 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDX8F93qEF3QnyVcTe:-NaG_D9V2HGxWohyVL17:b-xj91m9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These targets should be under a `testing` package in the `src/main` tree, with `default_testonly = True`. e.g. `//src/main/kotlin/org/wfanet/virtualpeople/core/selector/testing/testdata`
</blockquote></details>

Done. Could you please share why we do prefer have this under the src/main tree? thans
___
*[`src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel` line 7 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDWzarAbqjwqy_K50r:-NaGXNBJ3rcHad95Ug3o:b1ba7w1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

my bad. Don't need it.


<!-- Sent from Reviewable.io -->

2023-07-26 17:59 UTC, SanjayVas requested changes
> Reviewed 2 of 19 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 21 of 38 files reviewed, 32 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 35 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIANG7BuchxG5D7vcI:-NaIANG7BuchxG5D7vcJ:b2yf8dr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L35)):*
> ```Kotlin
> const val SECONDS_IN_A_DAY = 86_400L
> 
> class VidModelSelector(private val modelLine: ModelLine, private val rollouts: List<ModelRollout>) {
> ```

Public types and functions should have KDoc.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 62 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaI90cX7uPS-fjJCmHF:-NaI90cX7uPS-fjJCmHG:b3za84v) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L62)):*
> ```Kotlin
>     if (
>       eventTimestampSec >= modelLine.activeStartTime.seconds &&
>         eventTimestampSec < modelLine.activeEndTime.seconds
> ```

Make use of Kotlin/Java data structures related to time. More generally, you shouldn't ever need to directly access the subfields of a Timestamp message.

In this case, convert everything to `Instant` and compare that way.  We have an `org.wfanet.measurement.common.OpenEndTimeRange` type that corresponds to a protobuf Interval using `Instant`s. It has a `contains` operator so you can do things like

```kotlin
if (eventInstant in activeTimeRange) {
  // ...
}
```



_Code quote:_
```Kotlin
    val eventTimestampSec = labelerInput.timestampUsec / 1_000_000L
    if (
      eventTimestampSec >= modelLine.activeStartTime.seconds &&
        eventTimestampSec < modelLine.activeEndTime.seconds
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 124 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIBAMUD9w-rWDz8Q3W:-NaIBAMUD9w-rWDz8Q3X:b-a1oajv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L124)):*
> ```Kotlin
>    */
>   private fun calculatePercentages(eventDay: Long): ArrayList<ModelReleasePercentile> {
>     val activeRollouts = retrieveActiveRollouts(eventDay)
> ```

Specify types explicitly where not obvious (e.g. a constructor or factory call). The general idea is that one shouldn't have to hunt for the type when not using an IDE.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 125 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIAknb1aIpu0BopvwZ:-NaIAknb1aIpu0Bopvw_:b-7tgiwm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L125)):*
> ```Kotlin
>   private fun calculatePercentages(eventDay: Long): ArrayList<ModelReleasePercentile> {
>     val activeRollouts = retrieveActiveRollouts(eventDay)
>     val percentages = arrayListOf<ModelReleasePercentile>()
> ```

I assume you don't actually care about this being an ArrayList instance, but rather just any mutable random-access List implementation (it will likely end up being ArrayList underneath anyway).



_Suggestion:_
```Kotlin
mutableListOf
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 133 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIBeyK75ZHsWMplPfP:-NaIBeyK75ZHsWMplPfQ:b7razaf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L133)):*
> ```Kotlin
>         )
>       )
>     }
> ```

Iterable for loops are preferred for iterable collections. Even if the index is relevant, `forEachIndexed` is preferred. Numerical for loops are generally for cases where you're not just iterating over a collection.



_Suggestion:_
```Kotlin
    for (activeRollout in activeRollouts) {
      percentages.add(
        ModelReleasePercentile(
          calculatePercentageAdoption(eventDay, activeRollout),
          activeRollout.modelRelease
        )
      )
    }
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 178 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIGAOI4uT6BJ1Dcz3Z:-NaIGAOI4uT6BJ1Dcz3_:bt45gpm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L178)):*
> ```Kotlin
>       return rollouts
>     }
>     val sortedRollouts =
> ```

While this comment applies globally, I'm just noting explicit types here again as this is another time during this review that I had to "hunt" for the type.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 187 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIG0q2Eb6sIp57veDG:-NaIG0q2Eb6sIp57veDH:undefined) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L187)):*
> ```Kotlin
>       }
>     val firstRolloutPeriodStartDay =
>       if (sortedRollouts.elementAt(0).hasGradualRolloutPeriod()) {
> ```





_Suggestion:_
```Kotlin
first()
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 196 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIGcF64TOHY5p7pQEW:-NaIGcF64TOHY5p7pQEX:bcpo1n3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L196)):*
> ```Kotlin
>     }
>     val activeRollouts = arrayListOf<ModelRollout>()
>     for (i in sortedRollouts.size - 1 downTo 0) {
> ```

This looks like it can also be an iterable for loop.



_Suggestion:_
```Kotlin
for (rollout in sortedRollouts.asReversed())
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 224 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIHKmT6wKGOG9m6Zj4:-NaIHKmT6wKGOG9m6Zj5:b6d6nup) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L224)):*
> ```Kotlin
>     }
>     activeRollouts.reverse()
>     return activeRollouts
> ```

Do you actually need to reverse the elements in-place, or is a view sufficient? I only see the resulting list iterated over, so that should be fine.



_Suggestion:_
```Kotlin
    return activeRollouts.asReversed()
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 227 at r12](https://reviewable.io/revie [...]

2023-07-26 19:12 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 21 of 38 files reviewed, 31 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel` line 1 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDX8F93qEF3QnyVcTe:-NaIMSOO7QB6qadUcHN4:b-mjplf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel#L1)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done. Could you please share why we do prefer have this under the src/main tree? thans
</blockquote></details>

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#conventions. This still doesn't appear to be under a package named `testing`.

Basically the `src/test` tree is just for the tests themselves. Nothing in the `src/test` tree should be a dependency of something outside of the Bazel package in which its defined. Infrastructure for testing that isn't a test itself goes under a `testing` package in the `src/main` tree (except when it's something small, e.g. a helper class for a single test). The reasoning is that any larger infrastructure is more likely to either warrant its own tests and/or be useful to more than one test.


<!-- Sent from Reviewable.io -->

2023-07-26 19:13 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 21 of 38 files reviewed, 31 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, @stevenwarejones, and @wliue)

___
*[`src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel` line 1 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaDX8F93qEF3QnyVcTe:-NaIbT7R5LXCLXet3xFI:butgvq2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a47fa338090ef194bfb959f05b815018371f1131/src/test/proto/wfa/virtual_people/core/selector/test_data/BUILD.bazel#L1)):*
> Nothing in the `src/test` tree should be a dependency of something outside of the Bazel package in which its defined.

Another way to say this that might be clearer is that any BUILD target in the `src/test` tree should have a visibility of `private`.


<!-- Sent from Reviewable.io -->

2023-07-26 20:58 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r11, 17 of 19 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 37 of 38 files reviewed, 34 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, @SanjayVas, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 109 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#gh-1242529210:-NaIw0BGDHQjcELED5B4:b-hh7v8a) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/16162f3ed565df3e9e51f768919206b62f8bb828/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L109)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I see what the problem you were addressing is. I refactor the logic to fix the problem of labeling every event with all the ModelReleases.
@wliue @EvgSkv 
Only difference with the script provided by you Evgeny is that I don't iterate over the entire list of rollouts but just to those that still have some percentage of "penetration" and are not entirely replaced
</blockquote></details>

just to clarify @wliue - a frozen model might label a userId it hasn't labeled before.... that's too be expected if the hash of the userId falls within the frozen label range.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 133 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIBeyK75ZHsWMplPfP:-NaIxIBQ4gYngiph3tSC:b-qabxv8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Iterable for loops are preferred for iterable collections. Even if the index is relevant, `forEachIndexed` is preferred. Numerical for loops are generally for cases where you're not just iterating over a collection.
</blockquote></details>

why do we need a mutable list here at all?
```
val percentages = activeRollouts.map{ activeRollout->
        ModelReleasePercentile(
          calculatePercentageAdoption(eventDay, activeRollout),
          activeRollout.modelRelease
        )

}
```

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 190 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIxnXjE5Z3xmndZ0K_:-NaIxnXjE5Z3xmndZ0Ka:b-8iwdt1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L190)):*
> ```Kotlin
>         daysFromEpoch(sortedRollouts.elementAt(0).gradualRolloutPeriod.startDate)
>       } else {
>         daysFromEpoch(sortedRollouts.elementAt(0).instantRolloutDate)
> ```

ditto on the first
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 193 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIxzst4iTOEceR0Zb_:-NaIxzst4iTOEceR0Zba:bxujarv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L193)):*
> ```Kotlin
>       }
>     if (eventDay < firstRolloutPeriodStartDay) {
>       return arrayListOf()
> ```

```
return emptyList()
```

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 195 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIyBpqEsPgf1qXND9C:-NaIyBpqEsPgf1qXND9D:b-vtq5g9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L195)):*
> ```Kotlin
>       return arrayListOf()
>     }
>     val activeRollouts = arrayListOf<ModelRollout>()
> ```

ditto on Sanjay's earlier comment about just using a mutable list
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 224 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIHKmT6wKGOG9m6Zj4:-NaIybun7QQupP5pLnSC:b31h85e) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L224)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you actually need to reverse the elements in-place, or is a view sufficient? I only see the resulting list iterated over, so that should be fine.
</blockquote></details>

instead of reversing the list, why not just `prepend` the elements instead of using `add`?


<!-- Sent from Reviewable.io -->

2023-07-27 13:04 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 36 of 38 files reviewed, 34 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 109 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#gh-1242529210:-NaLSPOh-09DM_G_0VvU:b-4z1mw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/16162f3ed565df3e9e51f768919206b62f8bb828/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L109)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just to clarify @wliue - a frozen model might label a userId it hasn't labeled before.... that's too be expected if the hash of the userId falls within the frozen label range.
</blockquote></details>

that is correct, thanks @stevenwarejones . 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 35 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIANG7BuchxG5D7vcI:-NaLRAZ72T4GgFkKG2dS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Public types and functions should have KDoc.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 62 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaI90cX7uPS-fjJCmHF:-NaLb5gZBUS0t9dz2iDs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make use of Kotlin/Java data structures related to time. More generally, you shouldn't ever need to directly access the subfields of a Timestamp message.

In this case, convert everything to `Instant` and compare that way.  We have an `org.wfanet.measurement.common.OpenEndTimeRange` type that corresponds to a protobuf Interval using `Instant`s. It has a `contains` operator so you can do things like

```kotlin
if (eventInstant in activeTimeRange) {
  // ...
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 124 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIBAMUD9w-rWDz8Q3W:-NaLT3WR6-XqK5nNosy4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify types explicitly where not obvious (e.g. a constructor or factory call). The general idea is that one shouldn't have to hunt for the type when not using an IDE.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 125 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIAknb1aIpu0BopvwZ:-NaLUR-86vzBhsq-jmAh:b-x7wy00) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume you don't actually care about this being an ArrayList instance, but rather just any mutable random-access List implementation (it will likely end up being ArrayList underneath anyway).
</blockquote></details>

removed this line. See comment below
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 133 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIBeyK75ZHsWMplPfP:-NaLUKRQAG9NMSJomKyr:b7n61go) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L133)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why do we need a mutable list here at all?
```
val percentages = activeRollouts.map{ activeRollout->
        ModelReleasePercentile(
          calculatePercentageAdoption(eventDay, activeRollout),
          activeRollout.modelRelease
        )

}
```

</blockquote></details>

Right, there's no need for it
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 178 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIGAOI4uT6BJ1Dcz3Z:-NaMN1al3Rm9Felst4VL:b-q8jzb0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L178)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

While this comment applies globally, I'm just noting explicit types here again as this is another time during this review that I had to "hunt" for the type.
</blockquote></details>

got it
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 187 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIG0q2Eb6sIp57veDG:-NaLUsOO9AN7SyLCX5t5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L187)):*
> ```Kotlin
>       }
>     val firstRolloutPeriodStartDay =
>       if (sortedRollouts.elementAt(0).hasGradualRolloutPeriod()) {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 190 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIxnXjE5Z3xmndZ0K_:-NaLUsnFBnz2DCIPTvda:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L190)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on the first
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 193 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIxzst4iTOEceR0Zb_:-NaLUw811uuBtt9Kq0AD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L193)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```
return emptyList()
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 195 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/7 [...]

2023-07-27 15:28 UTC, stevenwarejones requested changes
> Reviewed 1 of 19 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 31 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @SanjayVas, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt` line 224 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIHKmT6wKGOG9m6Zj4:-NaMxQx-DS0SVAAn_83w:b-goaryy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/VidModelSelector.kt#L224)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I think prepending element at index 0, shifts everytime existing element to the right. ```asReversed``` looks more efficient to me
</blockquote></details>

i think you have this backwards. I thought prepend was faster than append. Just clock it and check.


<!-- Sent from Reviewable.io -->

2023-07-27 21:15 UTC, SanjayVas approved these changes
> Reviewed 17 of 19 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 16 unresolved discussions (waiting on @EvgSkv, @kungfucraig, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-27 21:21 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 16 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt` line 21 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73#-NaIDIXL8L9yzlLZBtjM:-NaOCW-KBZ-Z5a0NqkiV:b-4exbk1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/83e2adab1c4ccc06ab542879d81fd7594a17f673/src/main/kotlin/org/wfanet/virtualpeople/core/selector/LruCache.kt#L21)):*
> Do you have concerns if we explicitly use the synchronized mechanism [@SanjayVas](https://github.com/SanjayVas) ?

I was just thinking that the Guava cache might offer more granular locking for higher performance. Any time we don't have to write our own synchronization we avoid making a whole class of errors.

That said, if it's not just the cache that we're trying to guard then it sounds like we have to do our own synchronization anyway.


<!-- Sent from Reviewable.io -->

2023-07-27 22:38 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: all files reviewed, 16 unresolved discussions (waiting on @EvgSkv, @kungfucraig, @Marco-Premier, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-28 07:43 UTC, Marco-Premier reviewed
> Dismissed @wliue, and @wliue from 15 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: 34 of 38 files reviewed, all discussions resolved (waiting on @EvgSkv, @kungfucraig, @SanjayVas, @stevenwarejones, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-28 07:44 UTC, Marco-Premier reviewed
> Reviewed 3 of 23 files at r1, 1 of 13 files at r2, 8 of 15 files at r5, 2 of 6 files at r6, 1 of 11 files at r10, 1 of 3 files at r11, 18 of 19 files at r12, 1 of 1 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kungfucraig, and @wliue)



<!-- Sent from Reviewable.io -->

2023-07-28 07:50 UTC, merged